// Hero database for Chess Pal (data only)
// Loaded before `pages.js`
(() => {
  const g = (typeof window !== 'undefined') ? window : globalThis;
  g.CP_DATA = g.CP_DATA || {};

  g.CP_DATA.HERO_DB = [
    {
      id: '001',
      name: 'Aurex',
      element: 'light',
      role: 'support',
      rarity: 6,
      level: 1,
      maxLevel: 70,
      hp1: 300,
      atk1: 170,
      rcv1: 70,
      hpMax: 4200,
      atkMax: 1350,
      rcvMax: 520,
      leaderSkill: { text: 'Light heroes ATK ×1.6; heal +3% max HP each turn.', params: { atkMult: 1.6, healMaxHpPctPerTurn: 0.03 } },
      activeSkill: { name: 'Radiant Guard', cd: 7, text: 'Reduce damage -25% this turn; convert 2 random tiles to Light.', params: { damageReduction: 0.25, convert: { count: 2, to: 'light' } } },
      img: 'images/Heros/001-Aurex/001-Aurex.png',
      mini: 'images/Heros/001-Aurex/001-Aurex-mini.png'
    },
    {
      id: '002',
      name: 'Nyxblade',
      element: 'dark',
      role: 'striker',
      rarity: 7,
      level: 1,
      maxLevel: 80,
      hp1: 260,
      atk1: 230,
      rcv1: 35,
      hpMax: 4000,
      atkMax: 1750,
      rcvMax: 320,
      leaderSkill: { text: 'Dark heroes ATK ×1.7; each cascade adds +10% ATK (cap +40%).', params: { atkMult: 1.7, cascadeAtkBonusPer: 0.10, cascadeAtkBonusCap: 0.40 } },
      activeSkill: { name: 'Shadow Cut', cd: 6, text: 'Dark ATK ×1.3 this turn; convert 1 random tile to Dark.', params: { atkMultThisTurn: 1.3, convert: { count: 1, to: 'dark' } } },
      img: 'images/Heros/002-Nyxblade/002-Nyxblade.png',
      mini: 'images/Heros/002-Nyxblade/002-Nyxblade-mini.png'
    },
    {
      id: '003',
      name: 'Rivenhart',
      element: 'water',
      role: 'healer',
      rarity: 7,
      level: 1,
      maxLevel: 80,
      hp1: 280,
      atk1: 150,
      rcv1: 120,
      hpMax: 4100,
      atkMax: 1150,
      rcvMax: 920,
      leaderSkill: { text: 'Water heroes RCV ×1.6; +1s action time each turn.', params: { rcvMult: 1.6, extraTimeSec: 1 } },
      activeSkill: { name: 'Tide Reset', cd: 7, text: 'Clear 1 negative effect after cascades (placeholder); convert 2 random tiles to Water.', params: { clearNegativeCount: 1, convert: { count: 2, to: 'water' } } },
      img: 'images/Heros/003-Rivenhart/003-Rivenhart.png',
      mini: 'images/Heros/003-Rivenhart/003-Rivenhart-mini.png'
    },
    {
      id: '004',
      name: 'Seraphix',
      element: 'wood',
      role: 'tank',
      rarity: 7,
      level: 1,
      maxLevel: 80,
      hp1: 360,
      atk1: 155,
      rcv1: 55,
      hpMax: 5600,
      atkMax: 1200,
      rcvMax: 420,
      leaderSkill: { text: 'Wood heroes HP ×1.4; heal +5% max HP each turn.', params: { hpMult: 1.4, healMaxHpPctPerTurn: 0.05 } },
      activeSkill: { name: 'Verdant Bloom', cd: 8, text: 'Convert 2 random tiles to Wood and 1 tile to Heart.', params: { convert: [{ count: 2, to: 'wood' }, { count: 1, to: 'heart' }] } },
      img: 'images/Heros/004-Seraphix/004-Seraphix.png',
      mini: 'images/Heros/004-Seraphix/004-Seraphix-mini.png'
    },
    {
      id: '005',
      name: 'Valkor',
      element: 'fire',
      role: 'striker',
      rarity: 6,
      level: 1,
      maxLevel: 70,
      hp1: 290,
      atk1: 215,
      rcv1: 40,
      hpMax: 4100,
      atkMax: 1550,
      rcvMax: 300,
      leaderSkill: { text: 'Fire heroes HP ×1.3 and ATK ×1.5.', params: { hpMult: 1.3, atkMult: 1.5 } },
      activeSkill: { name: 'Inferno Rally', cd: 8, text: 'Convert 3 random tiles to Fire; Fire ATK ×1.2 this turn.', params: { convert: { count: 3, to: 'fire' }, atkMultThisTurn: 1.2 } },
      img: 'images/Heros/005-Valkor/005-Valkor.png',
      mini: 'images/Heros/005-Valkor/005-Valkor-mini.png'
    },

    // Generated roster (006-060): 1★..10★, 5 heroes each + extra 10★ set
    { id: '006', name: 'Emberwick', element: 'fire', role: 'striker', rarity: 1, level: 1, maxLevel: 30, hp1: 120, atk1: 90, rcv1: 20, hpMax: 900, atkMax: 420, rcvMax: 110,
      leaderSkill: { text: 'Fire heroes ATK ×1.1 (rookie).', params: { atkMult: 1.1 } },
      activeSkill: { name: 'Spark', cd: 6, text: 'Convert 1 random tile to Fire.', params: { convert: { count: 1, to: 'fire' } } },
      img: 'images/Heros/006-Emberwick/006-Emberwick.png', mini: 'images/Heros/006-Emberwick/006-Emberwick-mini.png' },
    { id: '007', name: 'Brooklet', element: 'water', role: 'balanced', rarity: 1, level: 1, maxLevel: 30, hp1: 140, atk1: 75, rcv1: 30, hpMax: 1050, atkMax: 360, rcvMax: 150,
      leaderSkill: { text: 'Water heroes HP ×1.05 (rookie).', params: { hpMult: 1.05 } },
      activeSkill: { name: 'Ripple', cd: 6, text: 'Convert 1 random tile to Water.', params: { convert: { count: 1, to: 'water' } } },
      img: 'images/Heros/007-Brooklet/007-Brooklet.png', mini: 'images/Heros/007-Brooklet/007-Brooklet-mini.png' },
    { id: '008', name: 'Thornkin', element: 'wood', role: 'tank', rarity: 1, level: 1, maxLevel: 30, hp1: 180, atk1: 55, rcv1: 15, hpMax: 1350, atkMax: 280, rcvMax: 90,
      leaderSkill: { text: 'Wood heroes HP ×1.08 (rookie).', params: { hpMult: 1.08 } },
      activeSkill: { name: 'Barkskin', cd: 7, text: 'Reduce damage -10% this turn.', params: { damageReduction: 0.10 } },
      img: 'images/Heros/008-Thornkin/008-Thornkin.png', mini: 'images/Heros/008-Thornkin/008-Thornkin-mini.png' },
    { id: '009', name: 'LumenSprout', element: 'light', role: 'support', rarity: 1, level: 1, maxLevel: 30, hp1: 150, atk1: 60, rcv1: 35, hpMax: 1100, atkMax: 300, rcvMax: 170,
      leaderSkill: { text: 'Light heroes RCV ×1.08 (rookie).', params: { rcvMult: 1.08 } },
      activeSkill: { name: 'Gleam', cd: 7, text: 'Convert 1 random tile to Light.', params: { convert: { count: 1, to: 'light' } } },
      img: 'images/Heros/009-LumenSprout/009-LumenSprout.png', mini: 'images/Heros/009-LumenSprout/009-LumenSprout-mini.png' },
    { id: '010', name: 'ShadeProwler', element: 'dark', role: 'striker', rarity: 1, level: 1, maxLevel: 30, hp1: 125, atk1: 95, rcv1: 18, hpMax: 920, atkMax: 440, rcvMax: 100,
      leaderSkill: { text: 'Dark heroes ATK ×1.1 (rookie).', params: { atkMult: 1.1 } },
      activeSkill: { name: 'Nip', cd: 6, text: 'Convert 1 random tile to Dark.', params: { convert: { count: 1, to: 'dark' } } },
      img: 'images/Heros/010-ShadeProwler/010-ShadeProwler.png', mini: 'images/Heros/010-ShadeProwler/010-ShadeProwler-mini.png' },

    { id: '011', name: 'CinderSquire', element: 'fire', role: 'balanced', rarity: 2, level: 1, maxLevel: 35, hp1: 150, atk1: 95, rcv1: 28, hpMax: 1350, atkMax: 520, rcvMax: 180,
      leaderSkill: { text: 'Fire heroes ATK ×1.12.', params: { atkMult: 1.12 } },
      activeSkill: { name: 'Ember Step', cd: 7, text: 'Convert 1 random tile to Fire.', params: { convert: { count: 1, to: 'fire' } } },
      img: 'images/Heros/011-CinderSquire/011-CinderSquire.png', mini: 'images/Heros/011-CinderSquire/011-CinderSquire-mini.png' },
    { id: '012', name: 'Tidemarch', element: 'water', role: 'support', rarity: 2, level: 1, maxLevel: 35, hp1: 170, atk1: 75, rcv1: 45, hpMax: 1500, atkMax: 420, rcvMax: 260,
      leaderSkill: { text: 'Water heroes RCV ×1.12.', params: { rcvMult: 1.12 } },
      activeSkill: { name: 'Cleanse', cd: 8, text: 'Convert 1 random tile to Water; clear 1 minor debuff (placeholder).', params: { convert: { count: 1, to: 'water' }, clearNegativeCount: 1 } },
      img: 'images/Heros/012-Tidemarch/012-Tidemarch.png', mini: 'images/Heros/012-Tidemarch/012-Tidemarch-mini.png' },
    { id: '013', name: 'Barkguard', element: 'wood', role: 'tank', rarity: 2, level: 1, maxLevel: 35, hp1: 210, atk1: 70, rcv1: 22, hpMax: 1850, atkMax: 430, rcvMax: 160,
      leaderSkill: { text: 'Wood heroes HP ×1.12.', params: { hpMult: 1.12 } },
      activeSkill: { name: 'Guard Stance', cd: 8, text: 'Reduce damage -12% this turn.', params: { damageReduction: 0.12 } },
      img: 'images/Heros/013-Barkguard/013-Barkguard.png', mini: 'images/Heros/013-Barkguard/013-Barkguard-mini.png' },
    { id: '014', name: 'SunlitAcolyte', element: 'light', role: 'healer', rarity: 2, level: 1, maxLevel: 35, hp1: 160, atk1: 65, rcv1: 60, hpMax: 1450, atkMax: 380, rcvMax: 360,
      leaderSkill: { text: 'Light heroes RCV ×1.15.', params: { rcvMult: 1.15 } },
      activeSkill: { name: 'Warmth', cd: 8, text: 'Heal a small amount (placeholder).', params: { healFlat: 120 } },
      img: 'images/Heros/014-SunlitAcolyte/014-SunlitAcolyte.png', mini: 'images/Heros/014-SunlitAcolyte/014-SunlitAcolyte-mini.png' },
    { id: '015', name: 'NightbladeInitiate', element: 'dark', role: 'striker', rarity: 2, level: 1, maxLevel: 35, hp1: 145, atk1: 115, rcv1: 20, hpMax: 1320, atkMax: 600, rcvMax: 150,
      leaderSkill: { text: 'Dark heroes ATK ×1.12.', params: { atkMult: 1.12 } },
      activeSkill: { name: 'Backstab', cd: 7, text: 'Dark ATK ×1.05 this turn (placeholder).', params: { atkMultThisTurn: 1.05 } },
      img: 'images/Heros/015-NightbladeInitiate/015-NightbladeInitiate.png', mini: 'images/Heros/015-NightbladeInitiate/015-NightbladeInitiate-mini.png' },

    { id: '016', name: 'PyreDuelist', element: 'fire', role: 'striker', rarity: 3, level: 1, maxLevel: 40, hp1: 180, atk1: 135, rcv1: 30, hpMax: 2100, atkMax: 850, rcvMax: 220,
      leaderSkill: { text: 'Fire heroes ATK ×1.15.', params: { atkMult: 1.15 } },
      activeSkill: { name: 'Flare Cut', cd: 8, text: 'Convert 2 random tiles to Fire.', params: { convert: { count: 2, to: 'fire' } } },
      img: 'images/Heros/016-PyreDuelist/016-PyreDuelist.png', mini: 'images/Heros/016-PyreDuelist/016-PyreDuelist-mini.png' },
    { id: '017', name: 'MistCantor', element: 'water', role: 'healer', rarity: 3, level: 1, maxLevel: 40, hp1: 190, atk1: 95, rcv1: 80, hpMax: 2200, atkMax: 620, rcvMax: 520,
      leaderSkill: { text: 'Water heroes RCV ×1.18.', params: { rcvMult: 1.18 } },
      activeSkill: { name: 'Mist Heal', cd: 9, text: 'Heal a moderate amount (placeholder).', params: { healFlat: 240 } },
      img: 'images/Heros/017-MistCantor/017-MistCantor.png', mini: 'images/Heros/017-MistCantor/017-MistCantor-mini.png' },
    { id: '018', name: 'VerdantWarden', element: 'wood', role: 'tank', rarity: 3, level: 1, maxLevel: 40, hp1: 250, atk1: 95, rcv1: 35, hpMax: 3000, atkMax: 640, rcvMax: 260,
      leaderSkill: { text: 'Wood heroes HP ×1.18.', params: { hpMult: 1.18 } },
      activeSkill: { name: 'Root Wall', cd: 9, text: 'Reduce damage -15% this turn.', params: { damageReduction: 0.15 } },
      img: 'images/Heros/018-VerdantWarden/018-VerdantWarden.png', mini: 'images/Heros/018-VerdantWarden/018-VerdantWarden-mini.png' },
    { id: '019', name: 'RadiantSentry', element: 'light', role: 'support', rarity: 3, level: 1, maxLevel: 40, hp1: 220, atk1: 110, rcv1: 60, hpMax: 2600, atkMax: 700, rcvMax: 420,
      leaderSkill: { text: 'Light heroes HP ×1.10 and RCV ×1.10.', params: { hpMult: 1.10, rcvMult: 1.10 } },
      activeSkill: { name: 'Beacon', cd: 9, text: 'Convert 2 random tiles to Light.', params: { convert: { count: 2, to: 'light' } } },
      img: 'images/Heros/019-RadiantSentry/019-RadiantSentry.png', mini: 'images/Heros/019-RadiantSentry/019-RadiantSentry-mini.png' },
    { id: '020', name: 'UmbralRaider', element: 'dark', role: 'striker', rarity: 3, level: 1, maxLevel: 40, hp1: 170, atk1: 155, rcv1: 28, hpMax: 2000, atkMax: 920, rcvMax: 210,
      leaderSkill: { text: 'Dark heroes ATK ×1.18.', params: { atkMult: 1.18 } },
      activeSkill: { name: 'Night Rush', cd: 8, text: 'Dark ATK ×1.08 this turn (placeholder).', params: { atkMultThisTurn: 1.08 } },
      img: 'images/Heros/020-UmbralRaider/020-UmbralRaider.png', mini: 'images/Heros/020-UmbralRaider/020-UmbralRaider-mini.png' },

    { id: '021', name: 'ScorchVanguard', element: 'fire', role: 'tank', rarity: 4, level: 1, maxLevel: 50, hp1: 260, atk1: 120, rcv1: 35, hpMax: 4200, atkMax: 980, rcvMax: 320,
      leaderSkill: { text: 'Fire heroes HP ×1.18.', params: { hpMult: 1.18 } },
      activeSkill: { name: 'Heat Guard', cd: 9, text: 'Reduce damage -18% this turn.', params: { damageReduction: 0.18 } },
      img: 'images/Heros/021-ScorchVanguard/021-ScorchVanguard.png', mini: 'images/Heros/021-ScorchVanguard/021-ScorchVanguard-mini.png' },
    { id: '022', name: 'GlacierScholar', element: 'water', role: 'support', rarity: 4, level: 1, maxLevel: 50, hp1: 240, atk1: 110, rcv1: 70, hpMax: 3900, atkMax: 900, rcvMax: 560,
      leaderSkill: { text: 'Water heroes RCV ×1.20.', params: { rcvMult: 1.20 } },
      activeSkill: { name: 'Study Flow', cd: 10, text: 'Convert 2 random tiles to Water; +0.5s time (placeholder).', params: { convert: { count: 2, to: 'water' }, extraTimeSec: 0.5 } },
      img: 'images/Heros/022-GlacierScholar/022-GlacierScholar.png', mini: 'images/Heros/022-GlacierScholar/022-GlacierScholar-mini.png' },
    { id: '023', name: 'BriarPaladin', element: 'wood', role: 'balanced', rarity: 4, level: 1, maxLevel: 50, hp1: 280, atk1: 130, rcv1: 45, hpMax: 4400, atkMax: 1050, rcvMax: 400,
      leaderSkill: { text: 'Wood heroes HP ×1.10 and ATK ×1.10.', params: { hpMult: 1.10, atkMult: 1.10 } },
      activeSkill: { name: 'Vine Blessing', cd: 10, text: 'Convert 1 tile to Wood and 1 tile to Heart.', params: { convert: [{ count: 1, to: 'wood' }, { count: 1, to: 'heart' }] } },
      img: 'images/Heros/023-BriarPaladin/023-BriarPaladin.png', mini: 'images/Heros/023-BriarPaladin/023-BriarPaladin-mini.png' },
    { id: '024', name: 'DawnArbiter', element: 'light', role: 'striker', rarity: 4, level: 1, maxLevel: 50, hp1: 230, atk1: 160, rcv1: 40, hpMax: 3800, atkMax: 1250, rcvMax: 350,
      leaderSkill: { text: 'Light heroes ATK ×1.20.', params: { atkMult: 1.20 } },
      activeSkill: { name: 'Judgement', cd: 10, text: 'Light ATK ×1.10 this turn (placeholder).', params: { atkMultThisTurn: 1.10 } },
      img: 'images/Heros/024-DawnArbiter/024-DawnArbiter.png', mini: 'images/Heros/024-DawnArbiter/024-DawnArbiter-mini.png' },
    { id: '025', name: 'DuskHexer', element: 'dark', role: 'healer', rarity: 4, level: 1, maxLevel: 50, hp1: 250, atk1: 120, rcv1: 85, hpMax: 4000, atkMax: 980, rcvMax: 720,
      leaderSkill: { text: 'Dark heroes RCV ×1.20.', params: { rcvMult: 1.20 } },
      activeSkill: { name: 'Night Mend', cd: 10, text: 'Heal a moderate amount (placeholder).', params: { healFlat: 380 } },
      img: 'images/Heros/025-DuskHexer/025-DuskHexer.png', mini: 'images/Heros/025-DuskHexer/025-DuskHexer-mini.png' },

    { id: '026', name: 'InfernalMarshal', element: 'fire', role: 'striker', rarity: 5, level: 1, maxLevel: 60, hp1: 300, atk1: 200, rcv1: 45, hpMax: 5200, atkMax: 1650, rcvMax: 420,
      leaderSkill: { text: 'Fire heroes ATK ×1.25.', params: { atkMult: 1.25 } },
      activeSkill: { name: 'Inferno Order', cd: 10, text: 'Convert 3 random tiles to Fire.', params: { convert: { count: 3, to: 'fire' } } },
      img: 'images/Heros/026-InfernalMarshal/026-InfernalMarshal.png', mini: 'images/Heros/026-InfernalMarshal/026-InfernalMarshal-mini.png' },
    { id: '027', name: 'CoralPriestess', element: 'water', role: 'healer', rarity: 5, level: 1, maxLevel: 60, hp1: 320, atk1: 150, rcv1: 120, hpMax: 5600, atkMax: 1250, rcvMax: 980,
      leaderSkill: { text: 'Water heroes RCV ×1.25.', params: { rcvMult: 1.25 } },
      activeSkill: { name: 'Coral Hymn', cd: 10, text: 'Heal a large amount (placeholder).', params: { healFlat: 520 } },
      img: 'images/Heros/027-CoralPriestess/027-CoralPriestess.png', mini: 'images/Heros/027-CoralPriestess/027-CoralPriestess-mini.png' },
    { id: '028', name: 'GroveTitan', element: 'wood', role: 'tank', rarity: 5, level: 1, maxLevel: 60, hp1: 420, atk1: 150, rcv1: 55, hpMax: 7200, atkMax: 1250, rcvMax: 520,
      leaderSkill: { text: 'Wood heroes HP ×1.25.', params: { hpMult: 1.25 } },
      activeSkill: { name: 'Titan Guard', cd: 11, text: 'Reduce damage -22% this turn.', params: { damageReduction: 0.22 } },
      img: 'images/Heros/028-GroveTitan/028-GroveTitan.png', mini: 'images/Heros/028-GroveTitan/028-GroveTitan-mini.png' },
    { id: '029', name: 'HaloStrategist', element: 'light', role: 'support', rarity: 5, level: 1, maxLevel: 60, hp1: 360, atk1: 170, rcv1: 90, hpMax: 6200, atkMax: 1450, rcvMax: 800,
      leaderSkill: { text: 'Light heroes HP ×1.10 and RCV ×1.20.', params: { hpMult: 1.10, rcvMult: 1.20 } },
      activeSkill: { name: 'Plan of Light', cd: 11, text: 'Convert 2 random tiles to Light and 1 to Heart.', params: { convert: [{ count: 2, to: 'light' }, { count: 1, to: 'heart' }] } },
      img: 'images/Heros/029-HaloStrategist/029-HaloStrategist.png', mini: 'images/Heros/029-HaloStrategist/029-HaloStrategist-mini.png' },
    { id: '030', name: 'VoidRonin', element: 'dark', role: 'striker', rarity: 5, level: 1, maxLevel: 60, hp1: 290, atk1: 230, rcv1: 40, hpMax: 5000, atkMax: 1800, rcvMax: 380,
      leaderSkill: { text: 'Dark heroes ATK ×1.25.', params: { atkMult: 1.25 } },
      activeSkill: { name: 'Void Draw', cd: 10, text: 'Convert 2 random tiles to Dark.', params: { convert: { count: 2, to: 'dark' } } },
      img: 'images/Heros/030-VoidRonin/030-VoidRonin.png', mini: 'images/Heros/030-VoidRonin/030-VoidRonin-mini.png' },

    { id: '031', name: 'CrimsonSovereign', element: 'fire', role: 'balanced', rarity: 6, level: 1, maxLevel: 70, hp1: 340, atk1: 230, rcv1: 55, hpMax: 6500, atkMax: 1950, rcvMax: 520,
      leaderSkill: { text: 'Fire heroes HP ×1.10 and ATK ×1.15.', params: { hpMult: 1.10, atkMult: 1.15 } },
      activeSkill: { name: 'Royal Blaze', cd: 11, text: 'Convert 3 random tiles to Fire; Fire ATK ×1.08 this turn.', params: { convert: { count: 3, to: 'fire' }, atkMultThisTurn: 1.08 } },
      img: 'images/Heros/031-CrimsonSovereign/031-CrimsonSovereign.png', mini: 'images/Heros/031-CrimsonSovereign/031-CrimsonSovereign-mini.png' },
    { id: '032', name: 'DeepseaOracle', element: 'water', role: 'support', rarity: 6, level: 1, maxLevel: 70, hp1: 360, atk1: 190, rcv1: 110, hpMax: 6900, atkMax: 1650, rcvMax: 980,
      leaderSkill: { text: 'Water heroes RCV ×1.30.', params: { rcvMult: 1.30 } },
      activeSkill: { name: 'Oracle Tide', cd: 12, text: 'Convert 2 random tiles to Water and 1 to Heart.', params: { convert: [{ count: 2, to: 'water' }, { count: 1, to: 'heart' }] } },
      img: 'images/Heros/032-DeepseaOracle/032-DeepseaOracle.png', mini: 'images/Heros/032-DeepseaOracle/032-DeepseaOracle-mini.png' },
    { id: '033', name: 'WildrootBastion', element: 'wood', role: 'tank', rarity: 6, level: 1, maxLevel: 70, hp1: 480, atk1: 185, rcv1: 60, hpMax: 8600, atkMax: 1550, rcvMax: 560,
      leaderSkill: { text: 'Wood heroes HP ×1.30.', params: { hpMult: 1.30 } },
      activeSkill: { name: 'Bastion', cd: 12, text: 'Reduce damage -25% this turn.', params: { damageReduction: 0.25 } },
      img: 'images/Heros/033-WildrootBastion/033-WildrootBastion.png', mini: 'images/Heros/033-WildrootBastion/033-WildrootBastion-mini.png' },
    { id: '034', name: 'SunflareJusticar', element: 'light', role: 'striker', rarity: 6, level: 1, maxLevel: 70, hp1: 330, atk1: 270, rcv1: 55, hpMax: 6200, atkMax: 2250, rcvMax: 520,
      leaderSkill: { text: 'Light heroes ATK ×1.30.', params: { atkMult: 1.30 } },
      activeSkill: { name: 'Sunflare', cd: 12, text: 'Convert 3 random tiles to Light.', params: { convert: { count: 3, to: 'light' } } },
      img: 'images/Heros/034-SunflareJusticar/034-SunflareJusticar.png', mini: 'images/Heros/034-SunflareJusticar/034-SunflareJusticar-mini.png' },
    { id: '035', name: 'NetherLiturgist', element: 'dark', role: 'healer', rarity: 6, level: 1, maxLevel: 70, hp1: 360, atk1: 200, rcv1: 140, hpMax: 7000, atkMax: 1700, rcvMax: 1250,
      leaderSkill: { text: 'Dark heroes RCV ×1.30.', params: { rcvMult: 1.30 } },
      activeSkill: { name: 'Abyss Heal', cd: 12, text: 'Heal a large amount (placeholder).', params: { healFlat: 720 } },
      img: 'images/Heros/035-NetherLiturgist/035-NetherLiturgist.png', mini: 'images/Heros/035-NetherLiturgist/035-NetherLiturgist-mini.png' },

    { id: '036', name: 'PhoenixExecutioner', element: 'fire', role: 'striker', rarity: 7, level: 1, maxLevel: 80, hp1: 380, atk1: 290, rcv1: 65, hpMax: 7600, atkMax: 2600, rcvMax: 650,
      leaderSkill: { text: 'Fire heroes ATK ×1.35.', params: { atkMult: 1.35 } },
      activeSkill: { name: 'Phoenix Dive', cd: 12, text: 'Fire ATK ×1.10 this turn; convert 2 tiles to Fire.', params: { atkMultThisTurn: 1.10, convert: { count: 2, to: 'fire' } } },
      img: 'images/Heros/036-PhoenixExecutioner/036-PhoenixExecutioner.png', mini: 'images/Heros/036-PhoenixExecutioner/036-PhoenixExecutioner-mini.png' },
    { id: '037', name: 'LeviathanChoir', element: 'water', role: 'healer', rarity: 7, level: 1, maxLevel: 80, hp1: 420, atk1: 210, rcv1: 180, hpMax: 8200, atkMax: 1900, rcvMax: 1700,
      leaderSkill: { text: 'Water heroes RCV ×1.35.', params: { rcvMult: 1.35 } },
      activeSkill: { name: 'Choir Tide', cd: 13, text: 'Heal a very large amount (placeholder).', params: { healFlat: 980 } },
      img: 'images/Heros/037-LeviathanChoir/037-LeviathanChoir.png', mini: 'images/Heros/037-LeviathanChoir/037-LeviathanChoir-mini.png' },
    { id: '038', name: 'EmeraldColossus', element: 'wood', role: 'tank', rarity: 7, level: 1, maxLevel: 80, hp1: 560, atk1: 210, rcv1: 70, hpMax: 10400, atkMax: 1750, rcvMax: 680,
      leaderSkill: { text: 'Wood heroes HP ×1.35.', params: { hpMult: 1.35 } },
      activeSkill: { name: 'Colossus Guard', cd: 13, text: 'Reduce damage -28% this turn.', params: { damageReduction: 0.28 } },
      img: 'images/Heros/038-EmeraldColossus/038-EmeraldColossus.png', mini: 'images/Heros/038-EmeraldColossus/038-EmeraldColossus-mini.png' },
    { id: '039', name: 'AuroraCovenant', element: 'light', role: 'support', rarity: 7, level: 1, maxLevel: 80, hp1: 480, atk1: 240, rcv1: 150, hpMax: 9400, atkMax: 2200, rcvMax: 1350,
      leaderSkill: { text: 'Light heroes HP ×1.15 and RCV ×1.25.', params: { hpMult: 1.15, rcvMult: 1.25 } },
      activeSkill: { name: 'Aurora Plan', cd: 13, text: 'Convert 2 tiles to Light and 2 tiles to Heart.', params: { convert: [{ count: 2, to: 'light' }, { count: 2, to: 'heart' }] } },
      img: 'images/Heros/039-AuroraCovenant/039-AuroraCovenant.png', mini: 'images/Heros/039-AuroraCovenant/039-AuroraCovenant-mini.png' },
    { id: '040', name: 'EclipseVagrant', element: 'dark', role: 'striker', rarity: 7, level: 1, maxLevel: 80, hp1: 370, atk1: 330, rcv1: 60, hpMax: 7300, atkMax: 2850, rcvMax: 600,
      leaderSkill: { text: 'Dark heroes ATK ×1.35.', params: { atkMult: 1.35 } },
      activeSkill: { name: 'Eclipse Step', cd: 12, text: 'Convert 3 tiles to Dark.', params: { convert: { count: 3, to: 'dark' } } },
      img: 'images/Heros/040-EclipseVagrant/040-EclipseVagrant.png', mini: 'images/Heros/040-EclipseVagrant/040-EclipseVagrant-mini.png' },

    { id: '041', name: 'SolarbrandRegent', element: 'fire', role: 'balanced', rarity: 8, level: 1, maxLevel: 90, hp1: 430, atk1: 330, rcv1: 80, hpMax: 9000, atkMax: 3000, rcvMax: 850,
      leaderSkill: { text: 'Fire heroes HP ×1.12 and ATK ×1.22.', params: { hpMult: 1.12, atkMult: 1.22 } },
      activeSkill: { name: 'Solarbrand', cd: 13, text: 'Convert 4 tiles to Fire.', params: { convert: { count: 4, to: 'fire' } } },
      img: 'images/Heros/041-SolarbrandRegent/041-SolarbrandRegent.png', mini: 'images/Heros/041-SolarbrandRegent/041-SolarbrandRegent-mini.png' },
    { id: '042', name: 'StarcurrentMatron', element: 'water', role: 'support', rarity: 8, level: 1, maxLevel: 90, hp1: 480, atk1: 270, rcv1: 170, hpMax: 9800, atkMax: 2500, rcvMax: 1800,
      leaderSkill: { text: 'Water heroes RCV ×1.40.', params: { rcvMult: 1.40 } },
      activeSkill: { name: 'Starcurrent', cd: 14, text: 'Convert 3 tiles to Water and 1 tile to Heart.', params: { convert: [{ count: 3, to: 'water' }, { count: 1, to: 'heart' }] } },
      img: 'images/Heros/042-StarcurrentMatron/042-StarcurrentMatron.png', mini: 'images/Heros/042-StarcurrentMatron/042-StarcurrentMatron-mini.png' },
    { id: '043', name: 'ThornCathedralKnight', element: 'wood', role: 'tank', rarity: 8, level: 1, maxLevel: 90, hp1: 650, atk1: 250, rcv1: 80, hpMax: 12000, atkMax: 2100, rcvMax: 800,
      leaderSkill: { text: 'Wood heroes HP ×1.40.', params: { hpMult: 1.40 } },
      activeSkill: { name: 'Cathedral Guard', cd: 14, text: 'Reduce damage -30% this turn.', params: { damageReduction: 0.30 } },
      img: 'images/Heros/043-ThornCathedralKnight/043-ThornCathedralKnight.png', mini: 'images/Heros/043-ThornCathedralKnight/043-ThornCathedralKnight-mini.png' },
    { id: '044', name: 'SeraphicVanguard', element: 'light', role: 'striker', rarity: 8, level: 1, maxLevel: 90, hp1: 420, atk1: 380, rcv1: 75, hpMax: 8600, atkMax: 3400, rcvMax: 780,
      leaderSkill: { text: 'Light heroes ATK ×1.40.', params: { atkMult: 1.40 } },
      activeSkill: { name: 'Seraph Strike', cd: 14, text: 'Light ATK ×1.12 this turn (placeholder).', params: { atkMultThisTurn: 1.12 } },
      img: 'images/Heros/044-SeraphicVanguard/044-SeraphicVanguard.png', mini: 'images/Heros/044-SeraphicVanguard/044-SeraphicVanguard-mini.png' },
    { id: '045', name: 'AbyssCanticle', element: 'dark', role: 'healer', rarity: 8, level: 1, maxLevel: 90, hp1: 470, atk1: 290, rcv1: 220, hpMax: 9800, atkMax: 2600, rcvMax: 2350,
      leaderSkill: { text: 'Dark heroes RCV ×1.40.', params: { rcvMult: 1.40 } },
      activeSkill: { name: 'Abyss Canticle', cd: 14, text: 'Heal a huge amount (placeholder).', params: { healFlat: 1400 } },
      img: 'images/Heros/045-AbyssCanticle/045-AbyssCanticle.png', mini: 'images/Heros/045-AbyssCanticle/045-AbyssCanticle-mini.png' },

    { id: '046', name: 'RadiantPyrelord', element: 'fire', role: 'striker', rarity: 9, level: 1, maxLevel: 100, hp1: 480, atk1: 420, rcv1: 95, hpMax: 10500, atkMax: 4100, rcvMax: 1100,
      leaderSkill: { text: 'Fire heroes ATK ×1.45.', params: { atkMult: 1.45 } },
      activeSkill: { name: 'Pyrelord', cd: 14, text: 'Convert 5 tiles to Fire.', params: { convert: { count: 5, to: 'fire' } } },
      img: 'images/Heros/046-RadiantPyrelord/046-RadiantPyrelord.png', mini: 'images/Heros/046-RadiantPyrelord/046-RadiantPyrelord-mini.png' },
    { id: '047', name: 'MoonlitTidemancer', element: 'water', role: 'healer', rarity: 9, level: 1, maxLevel: 100, hp1: 520, atk1: 320, rcv1: 260, hpMax: 11200, atkMax: 3000, rcvMax: 2900,
      leaderSkill: { text: 'Water heroes RCV ×1.45.', params: { rcvMult: 1.45 } },
      activeSkill: { name: 'Moonlit Tide', cd: 15, text: 'Heal an enormous amount (placeholder).', params: { healFlat: 1900 } },
      img: 'images/Heros/047-MoonlitTidemancer/047-MoonlitTidemancer.png', mini: 'images/Heros/047-MoonlitTidemancer/047-MoonlitTidemancer-mini.png' },
    { id: '048', name: 'WorldtreeSentinel', element: 'wood', role: 'tank', rarity: 9, level: 1, maxLevel: 100, hp1: 720, atk1: 300, rcv1: 90, hpMax: 14000, atkMax: 2500, rcvMax: 900,
      leaderSkill: { text: 'Wood heroes HP ×1.45.', params: { hpMult: 1.45 } },
      activeSkill: { name: 'Sentinel Guard', cd: 15, text: 'Reduce damage -32% this turn.', params: { damageReduction: 0.32 } },
      img: 'images/Heros/048-WorldtreeSentinel/048-WorldtreeSentinel.png', mini: 'images/Heros/048-WorldtreeSentinel/048-WorldtreeSentinel-mini.png' },
    { id: '049', name: 'SunoathHierophant', element: 'light', role: 'support', rarity: 9, level: 1, maxLevel: 100, hp1: 600, atk1: 360, rcv1: 220, hpMax: 12800, atkMax: 3300, rcvMax: 2500,
      leaderSkill: { text: 'Light heroes HP ×1.18 and RCV ×1.32.', params: { hpMult: 1.18, rcvMult: 1.32 } },
      activeSkill: { name: 'Sun Oath', cd: 15, text: 'Convert 3 tiles to Light and 3 tiles to Heart.', params: { convert: [{ count: 3, to: 'light' }, { count: 3, to: 'heart' }] } },
      img: 'images/Heros/049-SunoathHierophant/049-SunoathHierophant.png', mini: 'images/Heros/049-SunoathHierophant/049-SunoathHierophant-mini.png' },
    { id: '050', name: 'VoidbladeMonarch', element: 'dark', role: 'striker', rarity: 9, level: 1, maxLevel: 100, hp1: 460, atk1: 460, rcv1: 85, hpMax: 10000, atkMax: 4300, rcvMax: 1000,
      leaderSkill: { text: 'Dark heroes ATK ×1.45.', params: { atkMult: 1.45 } },
      activeSkill: { name: 'Monarch Cut', cd: 14, text: 'Dark ATK ×1.15 this turn (placeholder).', params: { atkMultThisTurn: 1.15 } },
      img: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch.png', mini: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch-mini.png' },

    { id: '051', name: 'DawnfireImperator', element: 'fire', role: 'balanced', rarity: 10, level: 1, maxLevel: 110, hp1: 540, atk1: 470, rcv1: 120, hpMax: 12500, atkMax: 5200, rcvMax: 1500,
      leaderSkill: { text: 'Fire heroes HP ×1.20 and ATK ×1.30.', params: { hpMult: 1.20, atkMult: 1.30 } },
      activeSkill: { name: 'Imperial Dawnfire', cd: 15, text: 'Convert 6 tiles to Fire.', params: { convert: { count: 6, to: 'fire' } } },
      img: 'images/Heros/051-DawnfireImperator/051-DawnfireImperator.png', mini: 'images/Heros/051-DawnfireImperator/051-DawnfireImperator-mini.png' },
    { id: '052', name: 'CelestialTidesaint', element: 'water', role: 'support', rarity: 10, level: 1, maxLevel: 110, hp1: 600, atk1: 380, rcv1: 260, hpMax: 13800, atkMax: 4200, rcvMax: 3400,
      leaderSkill: { text: 'Water heroes RCV ×1.55.', params: { rcvMult: 1.55 } },
      activeSkill: { name: 'Celestial Tide', cd: 16, text: 'Convert 4 tiles to Water and 4 tiles to Heart.', params: { convert: [{ count: 4, to: 'water' }, { count: 4, to: 'heart' }] } },
      img: 'images/Heros/052-CelestialTidesaint/052-CelestialTidesaint.png', mini: 'images/Heros/052-CelestialTidesaint/052-CelestialTidesaint-mini.png' },
    { id: '053', name: 'PrimordialVerdantKing', element: 'wood', role: 'tank', rarity: 10, level: 1, maxLevel: 110, hp1: 820, atk1: 340, rcv1: 110, hpMax: 17000, atkMax: 3500, rcvMax: 1200,
      leaderSkill: { text: 'Wood heroes HP ×1.55.', params: { hpMult: 1.55 } },
      activeSkill: { name: 'Verdant Crown', cd: 16, text: 'Reduce damage -35% this turn.', params: { damageReduction: 0.35 } },
      img: 'images/Heros/053-PrimordialVerdantKing/053-PrimordialVerdantKing.png', mini: 'images/Heros/053-PrimordialVerdantKing/053-PrimordialVerdantKing-mini.png' },
    { id: '054', name: 'ArcLumenSeraph', element: 'light', role: 'striker', rarity: 10, level: 1, maxLevel: 110, hp1: 520, atk1: 540, rcv1: 110, hpMax: 12000, atkMax: 5600, rcvMax: 1400,
      leaderSkill: { text: 'Light heroes ATK ×1.55.', params: { atkMult: 1.55 } },
      activeSkill: { name: 'Arc Lumen', cd: 16, text: 'Convert 6 tiles to Light.', params: { convert: { count: 6, to: 'light' } } },
      img: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph.png', mini: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph-mini.png' },
    { id: '055', name: 'UmbralEclipseSaint', element: 'dark', role: 'healer', rarity: 10, level: 1, maxLevel: 110, hp1: 580, atk1: 420, rcv1: 320, hpMax: 14000, atkMax: 4500, rcvMax: 4200,
      leaderSkill: { text: 'Dark heroes RCV ×1.55.', params: { rcvMult: 1.55 } },
      activeSkill: { name: 'Eclipse Sanctum', cd: 16, text: 'Heal an extreme amount (placeholder).', params: { healFlat: 2600 } },
      img: 'images/Heros/055-UmbralEclipseSaint/055-UmbralEclipseSaint.png', mini: 'images/Heros/055-UmbralEclipseSaint/055-UmbralEclipseSaint-mini.png' },

    { id: '056', name: 'BlazeCrownArchon', element: 'fire', role: 'striker', rarity: 10, level: 1, maxLevel: 110, hp1: 560, atk1: 560, rcv1: 110, hpMax: 12800, atkMax: 5900, rcvMax: 1450,
      leaderSkill: { text: 'Fire heroes ATK ×1.58.', params: { atkMult: 1.58 } },
      activeSkill: { name: 'Solar Cataclysm', cd: 16, text: 'Convert 6 tiles to Fire; Fire ATK ×1.12 this turn.', params: { convert: { count: 6, to: 'fire' }, atkMultThisTurn: 1.12 } },
      img: 'images/Heros/056-BlazeCrownArchon/056-BlazeCrownArchon.png', mini: 'images/Heros/056-BlazeCrownArchon/056-BlazeCrownArchon-mini.png' },
    { id: '057', name: 'TideglassSovereign', element: 'water', role: 'support', rarity: 10, level: 1, maxLevel: 110, hp1: 640, atk1: 390, rcv1: 300, hpMax: 14600, atkMax: 4450, rcvMax: 3700,
      leaderSkill: { text: 'Water heroes RCV ×1.58.', params: { rcvMult: 1.58 } },
      activeSkill: { name: 'Ocean Prayer', cd: 16, text: 'Convert 4 tiles to Water and 4 tiles to Heart; +1.0s action time this turn.', params: { convert: [{ count: 4, to: 'water' }, { count: 4, to: 'heart' }], extraTimeSec: 1.0 } },
      img: 'images/Heros/057-TideglassSovereign/057-TideglassSovereign.png', mini: 'images/Heros/057-TideglassSovereign/057-TideglassSovereign-mini.png' },
    { id: '058', name: 'VerdantAegisPrime', element: 'wood', role: 'tank', rarity: 10, level: 1, maxLevel: 110, hp1: 900, atk1: 360, rcv1: 120, hpMax: 17800, atkMax: 3700, rcvMax: 1300,
      leaderSkill: { text: 'Wood heroes HP ×1.58.', params: { hpMult: 1.58 } },
      activeSkill: { name: 'Ancient Bulwark', cd: 16, text: 'Reduce damage -36% this turn; convert 2 tiles to Wood.', params: { damageReduction: 0.36, convert: { count: 2, to: 'wood' } } },
      img: 'images/Heros/058-VerdantAegisPrime/058-VerdantAegisPrime.png', mini: 'images/Heros/058-VerdantAegisPrime/058-VerdantAegisPrime-mini.png' },
    { id: '059', name: 'AuroraJudicatorPrime', element: 'light', role: 'balanced', rarity: 10, level: 1, maxLevel: 110, hp1: 620, atk1: 520, rcv1: 180, hpMax: 13600, atkMax: 5600, rcvMax: 2100,
      leaderSkill: { text: 'Light heroes HP ×1.18 and ATK ×1.35.', params: { hpMult: 1.18, atkMult: 1.35 } },
      activeSkill: { name: 'Prism Verdict', cd: 16, text: 'Convert 5 tiles to Light and 2 tiles to Heart.', params: { convert: [{ count: 5, to: 'light' }, { count: 2, to: 'heart' }] } },
      img: 'images/Heros/059-AuroraJudicatorPrime/059-AuroraJudicatorPrime.png', mini: 'images/Heros/059-AuroraJudicatorPrime/059-AuroraJudicatorPrime-mini.png' },
    { id: '060', name: 'NightfallAbyssRegent', element: 'dark', role: 'healer', rarity: 10, level: 1, maxLevel: 110, hp1: 640, atk1: 450, rcv1: 340, hpMax: 15000, atkMax: 4900, rcvMax: 4500,
      leaderSkill: { text: 'Dark heroes RCV ×1.58.', params: { rcvMult: 1.58 } },
      activeSkill: { name: 'Abyss Benediction', cd: 16, text: 'Heal an extreme amount and convert 3 random tiles to Dark.', params: { healFlat: 3000, convert: { count: 3, to: 'dark' } } },
      img: 'images/Heros/060-NightfallAbyssRegent/060-NightfallAbyssRegent.png', mini: 'images/Heros/060-NightfallAbyssRegent/060-NightfallAbyssRegent-mini.png' },

    // Time Rift (Support) 7★-10★
    { id: '061', name: 'Rift Page', element: 'light', role: 'support', rarity: 7, level: 1, maxLevel: 90, hp1: 430, atk1: 260, rcv1: 210, hpMax: 9200, atkMax: 2350, rcvMax: 2350,
      leaderSkill: { text: 'All allies gain +1.0s move time each turn.', params: { extraTimeSec: 1.0 } },
      activeSkill: { name: 'Time Stitch', cd: 10, text: '+1.0s move time this turn and heal 600.', params: { extraTimeSec: 1.0, healFlat: 600 } },
      img: 'images/Heros/049-SunoathHierophant/049-SunoathHierophant.png', mini: 'images/Heros/049-SunoathHierophant/049-SunoathHierophant-mini.png' },
    { id: '062', name: 'Rift Bishop', element: 'water', role: 'support', rarity: 8, level: 1, maxLevel: 100, hp1: 500, atk1: 300, rcv1: 250, hpMax: 10800, atkMax: 2850, rcvMax: 2850,
      leaderSkill: { text: 'All allies gain +1.0s move time and Water RCV ×1.20.', params: { extraTimeSec: 1.0, rcvMult: 1.20 } },
      activeSkill: { name: 'Chrono Weave', cd: 10, text: '+1.2s move time this turn and convert 2 tiles to Heart.', params: { extraTimeSec: 1.2, convert: { count: 2, to: 'heart' } } },
      img: 'images/Heros/052-CelestialTidesaint/052-CelestialTidesaint.png', mini: 'images/Heros/052-CelestialTidesaint/052-CelestialTidesaint-mini.png' },
    { id: '063', name: 'Rift Magistrate', element: 'wood', role: 'support', rarity: 9, level: 1, maxLevel: 105, hp1: 590, atk1: 340, rcv1: 285, hpMax: 12600, atkMax: 3350, rcvMax: 3250,
      leaderSkill: { text: 'All allies gain +1.0s move time and HP ×1.10.', params: { extraTimeSec: 1.0, hpMult: 1.10 } },
      activeSkill: { name: 'Tick Distortion', cd: 9, text: '+1.5s move time this turn and reduce damage -20%.', params: { extraTimeSec: 1.5, damageReduction: 0.20 } },
      img: 'images/Heros/058-VerdantAegisPrime/058-VerdantAegisPrime.png', mini: 'images/Heros/058-VerdantAegisPrime/058-VerdantAegisPrime-mini.png' },
    { id: '064', name: 'Rift Sovereign', element: 'light', role: 'support', rarity: 10, level: 1, maxLevel: 110, hp1: 680, atk1: 390, rcv1: 320, hpMax: 14800, atkMax: 4100, rcvMax: 3800,
      leaderSkill: { text: 'All allies gain +1.0s move time, HP ×1.12 and RCV ×1.25.', params: { extraTimeSec: 1.0, hpMult: 1.12, rcvMult: 1.25 } },
      activeSkill: { name: 'Crown of Hours', cd: 9, text: '+1.8s move time this turn, heal 1200, and convert 3 tiles to Heart.', params: { extraTimeSec: 1.8, healFlat: 1200, convert: { count: 3, to: 'heart' } } },
      img: 'images/Heros/059-AuroraJudicatorPrime/059-AuroraJudicatorPrime.png', mini: 'images/Heros/059-AuroraJudicatorPrime/059-AuroraJudicatorPrime-mini.png' },

    // Blood Pact (Risk/Reward) Hero 6★-10★
    { id: '065', name: 'Pact Swordsman', element: 'fire', role: 'striker', rarity: 6, level: 1, maxLevel: 80, hp1: 340, atk1: 290, rcv1: 90, hpMax: 6500, atkMax: 2600, rcvMax: 900,
      leaderSkill: { text: 'Fire heroes ATK ×1.22.', params: { atkMult: 1.22 } },
      activeSkill: { name: 'Blood Pact I', cd: 3, text: 'Lose 10% HP; ATK ×1.50 this turn.', params: { selfHpCostPct: 0.10, atkMultThisTurn: 1.50 } },
      img: 'images/Heros/041-SolarbrandRegent/041-SolarbrandRegent.png', mini: 'images/Heros/041-SolarbrandRegent/041-SolarbrandRegent-mini.png' },
    { id: '066', name: 'Pact Duelist', element: 'dark', role: 'striker', rarity: 7, level: 1, maxLevel: 90, hp1: 390, atk1: 340, rcv1: 95, hpMax: 7900, atkMax: 3250, rcvMax: 980,
      leaderSkill: { text: 'Dark heroes ATK ×1.26.', params: { atkMult: 1.26 } },
      activeSkill: { name: 'Blood Pact II', cd: 3, text: 'Lose 10% HP; ATK ×1.56 this turn.', params: { selfHpCostPct: 0.10, atkMultThisTurn: 1.56 } },
      img: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch.png', mini: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch-mini.png' },
    { id: '067', name: 'Pact Vanguard', element: 'wood', role: 'balanced', rarity: 8, level: 1, maxLevel: 100, hp1: 500, atk1: 370, rcv1: 110, hpMax: 9800, atkMax: 3650, rcvMax: 1200,
      leaderSkill: { text: 'Wood heroes HP ×1.10 and ATK ×1.24.', params: { hpMult: 1.10, atkMult: 1.24 } },
      activeSkill: { name: 'Blood Pact III', cd: 3, text: 'Lose 10% HP; ATK ×1.62 this turn.', params: { selfHpCostPct: 0.10, atkMultThisTurn: 1.62 } },
      img: 'images/Heros/043-ThornCathedralKnight/043-ThornCathedralKnight.png', mini: 'images/Heros/043-ThornCathedralKnight/043-ThornCathedralKnight-mini.png' },
    { id: '068', name: 'Pact Paragon', element: 'light', role: 'balanced', rarity: 9, level: 1, maxLevel: 105, hp1: 590, atk1: 420, rcv1: 125, hpMax: 11800, atkMax: 4350, rcvMax: 1450,
      leaderSkill: { text: 'Light heroes HP ×1.12 and ATK ×1.26.', params: { hpMult: 1.12, atkMult: 1.26 } },
      activeSkill: { name: 'Blood Pact IV', cd: 3, text: 'Lose 10% HP; ATK ×1.68 this turn.', params: { selfHpCostPct: 0.10, atkMultThisTurn: 1.68 } },
      img: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph.png', mini: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph-mini.png' },
    { id: '069', name: 'Pact Archlord', element: 'fire', role: 'striker', rarity: 10, level: 1, maxLevel: 110, hp1: 680, atk1: 500, rcv1: 140, hpMax: 14000, atkMax: 5200, rcvMax: 1650,
      leaderSkill: { text: 'Fire heroes HP ×1.12 and ATK ×1.30.', params: { hpMult: 1.12, atkMult: 1.30 } },
      activeSkill: { name: 'Blood Pact V', cd: 3, text: 'Lose 10% HP; ATK ×1.75 this turn.', params: { selfHpCostPct: 0.10, atkMultThisTurn: 1.75 } },
      img: 'images/Heros/056-BlazeCrownArchon/056-BlazeCrownArchon.png', mini: 'images/Heros/056-BlazeCrownArchon/056-BlazeCrownArchon-mini.png' },

    // Execution Mark (Assassin) Hero 8★-10★
    { id: '070', name: 'Marked Blade', element: 'dark', role: 'striker', rarity: 8, level: 1, maxLevel: 100, hp1: 450, atk1: 410, rcv1: 100, hpMax: 9000, atkMax: 4000, rcvMax: 1050,
      leaderSkill: { text: 'Dark heroes ATK ×1.28.', params: { atkMult: 1.28 } },
      activeSkill: { name: 'Execution Mark I', cd: 3, text: 'If target HP <30%, deal extra fixed damage.', params: { executeThresholdPct: 0.30, executeFlatBonus: 220 } },
      img: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch.png', mini: 'images/Heros/050-VoidbladeMonarch/050-VoidbladeMonarch-mini.png' },
    { id: '071', name: 'Marked Arbiter', element: 'light', role: 'striker', rarity: 9, level: 1, maxLevel: 105, hp1: 520, atk1: 470, rcv1: 110, hpMax: 10800, atkMax: 4700, rcvMax: 1200,
      leaderSkill: { text: 'Light heroes ATK ×1.32.', params: { atkMult: 1.32 } },
      activeSkill: { name: 'Execution Mark II', cd: 3, text: 'If target HP <30%, deal extra fixed damage.', params: { executeThresholdPct: 0.30, executeFlatBonus: 320 } },
      img: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph.png', mini: 'images/Heros/054-ArcLumenSeraph/054-ArcLumenSeraph-mini.png' },
    { id: '072', name: 'Marked Exarch', element: 'dark', role: 'striker', rarity: 10, level: 1, maxLevel: 110, hp1: 600, atk1: 540, rcv1: 125, hpMax: 12600, atkMax: 5500, rcvMax: 1450,
      leaderSkill: { text: 'Dark heroes ATK ×1.36.', params: { atkMult: 1.36 } },
      activeSkill: { name: 'Execution Mark III', cd: 3, text: 'If target HP <30%, deal extra fixed damage.', params: { executeThresholdPct: 0.30, executeFlatBonus: 450 } },
      img: 'images/Heros/060-NightfallAbyssRegent/060-NightfallAbyssRegent.png', mini: 'images/Heros/060-NightfallAbyssRegent/060-NightfallAbyssRegent-mini.png' }
  ];
})();

