// Monster database for Chess Pal (data only)
// Loaded before `pages.js`
(() => {
  const g = (typeof window !== 'undefined') ? window : globalThis;
  g.CP_DATA = g.CP_DATA || {};

  g.CP_DATA.MONSTER_DB = [
    {
      id: '001',
      name: 'Grimjaw',
      element: 'dark',
      rarity: 5,
      level: 1,
      maxLevel: 99,
      hp: 420,
      atk: 120,
      rcv: 0,
      passiveSkill: { name: 'Predator Instinct', text: 'ATK +10% when HP below 50% (placeholder).', params: { lowHpAtkBonus: 0.10 } },
      activeSkill: { name: 'Night Rend', cd: 6, text: 'Deal dark damage (placeholder).', params: { dmg: 120 } },
      img: 'images/Monsters/M001-Grimjaw/M001-Grimjaw.png',
      mini: 'images/Monsters/M001-Grimjaw/M001-Grimjaw-mini.png'
    },
    {
      id: '002',
      name: 'Cinder Brute',
      element: 'fire',
      rarity: 5,
      level: 1,
      maxLevel: 99,
      hp: 480,
      atk: 135,
      rcv: 0,
      passiveSkill: { name: 'Heat Armor', text: 'Take -10% damage (placeholder).', params: { damageReduction: 0.10 } },
      activeSkill: { name: 'Ash Slam', cd: 7, text: 'Convert 2 tiles to Fire (placeholder).', params: { convert: { count: 2, to: 'fire' } } },
      img: 'images/Monsters/M002-Cinder_Brute/M002-Cinder_Brute.png',
      mini: 'images/Monsters/M002-Cinder_Brute/M002-Cinder_Brute-mini.png'
    },
    {
      id: '003',
      name: 'Tide Wraith',
      element: 'water',
      rarity: 5,
      level: 1,
      maxLevel: 99,
      hp: 400,
      atk: 128,
      rcv: 0,
      passiveSkill: { name: 'Cold Mist', text: '10% chance to slow enemies (placeholder).', params: { slowChance: 0.10 } },
      activeSkill: { name: 'Undertow', cd: 6, text: 'Convert 1 tile to Water (placeholder).', params: { convert: { count: 1, to: 'water' } } },
      img: 'images/Monsters/M003-Tide_Wraith/M003-Tide_Wraith.png',
      mini: 'images/Monsters/M003-Tide_Wraith/M003-Tide_Wraith-mini.png'
    },
    {
      id: '004',
      name: 'Verdant Maw',
      element: 'wood',
      rarity: 5,
      level: 1,
      maxLevel: 99,
      hp: 520,
      atk: 110,
      rcv: 0,
      passiveSkill: { name: 'Regrowth', text: 'Heal +2% max HP each turn (placeholder).', params: { healMaxHpPctPerTurn: 0.02 } },
      activeSkill: { name: 'Root Bind', cd: 8, text: 'Convert 1 tile to Wood + 1 to Heart (placeholder).', params: { convert: [{ count: 1, to: 'wood' }, { count: 1, to: 'heart' }] } },
      img: 'images/Monsters/M004-Verdant_Maw/M004-Verdant_Maw.png',
      mini: 'images/Monsters/M004-Verdant_Maw/M004-Verdant_Maw-mini.png'
    },
    {
      id: '005',
      name: 'Solar Idol',
      element: 'light',
      rarity: 5,
      level: 1,
      maxLevel: 99,
      hp: 390,
      atk: 140,
      rcv: 0,
      passiveSkill: { name: 'Blinding Aura', text: 'Enemies miss +5% (placeholder).', params: { enemyMissChance: 0.05 } },
      activeSkill: { name: 'Radiant Pulse', cd: 7, text: 'Convert 2 tiles to Light (placeholder).', params: { convert: { count: 2, to: 'light' } } },
      img: 'images/Monsters/M005-Solar_Idol/M005-Solar_Idol.png',
      mini: 'images/Monsters/M005-Solar_Idol/M005-Solar_Idol-mini.png'
    },

    // Boss series (006-010)
    {
      id: '006',
      name: 'Abyss Monarch',
      element: 'dark',
      rarity: 6,
      level: 1,
      maxLevel: 99,
      hp: 880,
      atk: 210,
      rcv: 0,
      passiveSkill: { name: 'Abyssal Dominion', text: 'ATK +8% while active.', params: { atkBonus: 0.08 } },
      activeSkill: { name: 'Void Eclipse', cd: 9, text: 'Convert 3 tiles to Dark; deal heavy dark damage (placeholder).', params: { convert: { count: 3, to: 'dark' }, dmg: 360 } },
      img: 'images/Monsters/M006-Abyss_Monarch/M006-Abyss_Monarch.png',
      mini: 'images/Monsters/M006-Abyss_Monarch/M006-Abyss_Monarch-mini.png'
    },
    {
      id: '007',
      name: 'Crimson Warlord',
      element: 'fire',
      rarity: 6,
      level: 1,
      maxLevel: 99,
      hp: 920,
      atk: 225,
      rcv: 0,
      passiveSkill: { name: 'War Drums', text: 'Fire damage +15% (placeholder).', params: { fireDmgBonus: 0.15 } },
      activeSkill: { name: 'Blood Furnace', cd: 9, text: 'Convert 4 tiles to Fire (placeholder).', params: { convert: { count: 4, to: 'fire' } } },
      img: 'images/Monsters/M007-Crimson_Warlord/M007-Crimson_Warlord.png',
      mini: 'images/Monsters/M007-Crimson_Warlord/M007-Crimson_Warlord-mini.png'
    },
    {
      id: '008',
      name: 'Leviathan Prime',
      element: 'water',
      rarity: 6,
      level: 1,
      maxLevel: 99,
      hp: 860,
      atk: 220,
      rcv: 0,
      passiveSkill: { name: 'Deep Pressure', text: 'ATK +10% while active.', params: { atkBonus: 0.10 } },
      activeSkill: { name: 'Tsunami Break', cd: 10, text: 'Convert 3 tiles to Water; +1s time this turn (placeholder).', params: { convert: { count: 3, to: 'water' }, extraTimeSec: 1 } },
      img: 'images/Monsters/M008-Leviathan_Prime/M008-Leviathan_Prime.png',
      mini: 'images/Monsters/M008-Leviathan_Prime/M008-Leviathan_Prime-mini.png'
    },
    {
      id: '009',
      name: 'Worldroot Colossus',
      element: 'wood',
      rarity: 6,
      level: 1,
      maxLevel: 99,
      hp: 980,
      atk: 200,
      rcv: 0,
      passiveSkill: { name: 'Ancient Bark', text: 'Take -15% damage (placeholder).', params: { damageReduction: 0.15 } },
      activeSkill: { name: 'Thorn Cathedral', cd: 10, text: 'Convert 2 tiles to Wood + 2 to Heart (placeholder).', params: { convert: [{ count: 2, to: 'wood' }, { count: 2, to: 'heart' }] } },
      img: 'images/Monsters/M009-Worldroot_Colossus/M009-Worldroot_Colossus.png',
      mini: 'images/Monsters/M009-Worldroot_Colossus/M009-Worldroot_Colossus-mini.png'
    },
    {
      id: '010',
      name: 'Dawn Seraph',
      element: 'light',
      rarity: 6,
      level: 1,
      maxLevel: 99,
      hp: 840,
      atk: 235,
      rcv: 0,
      passiveSkill: { name: 'Radiant Shield', text: 'Heal +2% max HP each turn (placeholder).', params: { healMaxHpPctPerTurn: 0.02 } },
      activeSkill: { name: 'Solar Judgement', cd: 10, text: 'Convert 4 tiles to Light; deal light damage (placeholder).', params: { convert: { count: 4, to: 'light' }, dmg: 340 } },
      img: 'images/Monsters/M010-Dawn_Seraph/M010-Dawn_Seraph.png',
      mini: 'images/Monsters/M010-Dawn_Seraph/M010-Dawn_Seraph-mini.png'
    },

    // ----------------------------
    // Generated monsters (011-075)
    // Rarity counts target:
    // 1★-4★: 10 each (011-050)
    // 5★: +5 here to reach 10 total (051-055) since 001-005 already exist
    // 6★: keep 006-010 (already 5)
    // 7★-10★: 5 each (056-075)
    // ----------------------------

    // 1★ (011-020)
    { id:'011', name:'Ember Slime', element:'fire', rarity:1, level:1, maxLevel:99, hp:210, atk:55, rcv:0,
      passiveSkill:{ name:'Hot Core', text:'ATK +5% (placeholder).', params:{ atkBonus:0.05 } },
      activeSkill:{ name:'Singe', cd:6, text:'Deal small Fire damage (placeholder).', params:{ dmg:60 } },
      img:'images/Monsters/M011-Ember_Slime/M011-Ember_Slime.png', mini:'images/Monsters/M011-Ember_Slime/M011-Ember_Slime-mini.png' },
    { id:'012', name:'Cinder Imp', element:'fire', rarity:1, level:1, maxLevel:99, hp:190, atk:60, rcv:0,
      passiveSkill:{ name:'Ash Steps', text:'Move speed + (placeholder).', params:{ } },
      activeSkill:{ name:'Coal Toss', cd:6, text:'Deal small Fire damage (placeholder).', params:{ dmg:65 } },
      img:'images/Monsters/M012-Cinder_Imp/M012-Cinder_Imp.png', mini:'images/Monsters/M012-Cinder_Imp/M012-Cinder_Imp-mini.png' },
    { id:'013', name:'Spark Moth', element:'fire', rarity:1, level:1, maxLevel:99, hp:180, atk:50, rcv:0,
      passiveSkill:{ name:'Flicker', text:'Evasion +2% (placeholder).', params:{ evasion:0.02 } },
      activeSkill:{ name:'Flash Ember', cd:7, text:'Convert 1 tile to Fire (placeholder).', params:{ convert:{ count:1, to:'fire' } } },
      img:'images/Monsters/M013-Spark_Moth/M013-Spark_Moth.png', mini:'images/Monsters/M013-Spark_Moth/M013-Spark_Moth-mini.png' },
    { id:'014', name:'River Blob', element:'water', rarity:1, level:1, maxLevel:99, hp:230, atk:48, rcv:0,
      passiveSkill:{ name:'Soak', text:'Take -3% damage (placeholder).', params:{ damageReduction:0.03 } },
      activeSkill:{ name:'Splash', cd:6, text:'Deal small Water damage (placeholder).', params:{ dmg:58 } },
      img:'images/Monsters/M014-River_Blob/M014-River_Blob.png', mini:'images/Monsters/M014-River_Blob/M014-River_Blob-mini.png' },
    { id:'015', name:'Mist Sprite', element:'water', rarity:1, level:1, maxLevel:99, hp:200, atk:52, rcv:0,
      passiveSkill:{ name:'Fog Veil', text:'Evasion +2% (placeholder).', params:{ evasion:0.02 } },
      activeSkill:{ name:'Droplet', cd:7, text:'Convert 1 tile to Water (placeholder).', params:{ convert:{ count:1, to:'water' } } },
      img:'images/Monsters/M015-Mist_Sprite/M015-Mist_Sprite.png', mini:'images/Monsters/M015-Mist_Sprite/M015-Mist_Sprite-mini.png' },
    { id:'016', name:'Pond Crab', element:'water', rarity:1, level:1, maxLevel:99, hp:260, atk:46, rcv:0,
      passiveSkill:{ name:'Shell', text:'Take -4% damage (placeholder).', params:{ damageReduction:0.04 } },
      activeSkill:{ name:'Pinch', cd:6, text:'Deal small Water damage (placeholder).', params:{ dmg:55 } },
      img:'images/Monsters/M016-Pond_Crab/M016-Pond_Crab.png', mini:'images/Monsters/M016-Pond_Crab/M016-Pond_Crab-mini.png' },
    { id:'017', name:'Sproutling', element:'wood', rarity:1, level:1, maxLevel:99, hp:240, atk:47, rcv:0,
      passiveSkill:{ name:'Photosynthesis', text:'Heal +1% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.01 } },
      activeSkill:{ name:'Leaf Tap', cd:7, text:'Convert 1 tile to Wood (placeholder).', params:{ convert:{ count:1, to:'wood' } } },
      img:'images/Monsters/M017-Sproutling/M017-Sproutling.png', mini:'images/Monsters/M017-Sproutling/M017-Sproutling-mini.png' },
    { id:'018', name:'Bark Beetle', element:'wood', rarity:1, level:1, maxLevel:99, hp:250, atk:44, rcv:0,
      passiveSkill:{ name:'Hard Carapace', text:'Take -4% damage (placeholder).', params:{ damageReduction:0.04 } },
      activeSkill:{ name:'Nibble', cd:6, text:'Deal small Wood damage (placeholder).', params:{ dmg:54 } },
      img:'images/Monsters/M018-Bark_Beetle/M018-Bark_Beetle.png', mini:'images/Monsters/M018-Bark_Beetle/M018-Bark_Beetle-mini.png' },
    { id:'019', name:'Sun Wisp', element:'light', rarity:1, level:1, maxLevel:99, hp:200, atk:55, rcv:0,
      passiveSkill:{ name:'Glow', text:'Light damage +3% (placeholder).', params:{ lightDmgBonus:0.03 } },
      activeSkill:{ name:'Glimmer', cd:7, text:'Convert 1 tile to Light (placeholder).', params:{ convert:{ count:1, to:'light' } } },
      img:'images/Monsters/M019-Sun_Wisp/M019-Sun_Wisp.png', mini:'images/Monsters/M019-Sun_Wisp/M019-Sun_Wisp-mini.png' },
    { id:'020', name:'Shade Bat', element:'dark', rarity:1, level:1, maxLevel:99, hp:190, atk:58, rcv:0,
      passiveSkill:{ name:'Night Sight', text:'Crit +2% (placeholder).', params:{ crit:0.02 } },
      activeSkill:{ name:'Screech', cd:7, text:'Deal small Dark damage (placeholder).', params:{ dmg:62 } },
      img:'images/Monsters/M020-Shade_Bat/M020-Shade_Bat.png', mini:'images/Monsters/M020-Shade_Bat/M020-Shade_Bat-mini.png' },

    // 2★ (021-030)
    { id:'021', name:'Blazehound Pup', element:'fire', rarity:2, level:1, maxLevel:99, hp:320, atk:78, rcv:0,
      passiveSkill:{ name:'Heat Fang', text:'ATK +6% (placeholder).', params:{ atkBonus:0.06 } },
      activeSkill:{ name:'Flame Bite', cd:7, text:'Deal Fire damage (placeholder).', params:{ dmg:90 } },
      img:'images/Monsters/M021-Blazehound_Pup/M021-Blazehound_Pup.png', mini:'images/Monsters/M021-Blazehound_Pup/M021-Blazehound_Pup-mini.png' },
    { id:'022', name:'Charcoal Golem', element:'fire', rarity:2, level:1, maxLevel:99, hp:360, atk:72, rcv:0,
      passiveSkill:{ name:'Warm Armor', text:'Take -6% damage (placeholder).', params:{ damageReduction:0.06 } },
      activeSkill:{ name:'Smolder Smash', cd:8, text:'Deal Fire damage (placeholder).', params:{ dmg:95 } },
      img:'images/Monsters/M022-Charcoal_Golem/M022-Charcoal_Golem.png', mini:'images/Monsters/M022-Charcoal_Golem/M022-Charcoal_Golem-mini.png' },
    { id:'023', name:'Steam Drakelet', element:'fire', rarity:2, level:1, maxLevel:99, hp:280, atk:85, rcv:0,
      passiveSkill:{ name:'Boil', text:'Fire damage +5% (placeholder).', params:{ fireDmgBonus:0.05 } },
      activeSkill:{ name:'Steam Jet', cd:8, text:'Convert 1 tile to Fire (placeholder).', params:{ convert:{ count:1, to:'fire' } } },
      img:'images/Monsters/M023-Steam_Drakelet/M023-Steam_Drakelet.png', mini:'images/Monsters/M023-Steam_Drakelet/M023-Steam_Drakelet-mini.png' },
    { id:'024', name:'Icefin', element:'water', rarity:2, level:1, maxLevel:99, hp:300, atk:80, rcv:0,
      passiveSkill:{ name:'Chill', text:'Chance to slow (placeholder).', params:{ slowChance:0.05 } },
      activeSkill:{ name:'Frost Splash', cd:7, text:'Deal Water damage (placeholder).', params:{ dmg:92 } },
      img:'images/Monsters/M024-Icefin/M024-Icefin.png', mini:'images/Monsters/M024-Icefin/M024-Icefin-mini.png' },
    { id:'025', name:'Tidal Jelly', element:'water', rarity:2, level:1, maxLevel:99, hp:340, atk:70, rcv:0,
      passiveSkill:{ name:'Elastic', text:'Take -5% damage (placeholder).', params:{ damageReduction:0.05 } },
      activeSkill:{ name:'Wave Pop', cd:8, text:'Convert 2 tiles to Water (placeholder).', params:{ convert:{ count:2, to:'water' } } },
      img:'images/Monsters/M025-Tidal_Jelly/M025-Tidal_Jelly.png', mini:'images/Monsters/M025-Tidal_Jelly/M025-Tidal_Jelly-mini.png' },
    { id:'026', name:'Harbor Sentinel', element:'water', rarity:2, level:1, maxLevel:99, hp:360, atk:74, rcv:0,
      passiveSkill:{ name:'Anchor', text:'Take -6% damage (placeholder).', params:{ damageReduction:0.06 } },
      activeSkill:{ name:'Undertow Hook', cd:8, text:'Deal Water damage (placeholder).', params:{ dmg:96 } },
      img:'images/Monsters/M026-Harbor_Sentinel/M026-Harbor_Sentinel.png', mini:'images/Monsters/M026-Harbor_Sentinel/M026-Harbor_Sentinel-mini.png' },
    { id:'027', name:'Vine Lurker', element:'wood', rarity:2, level:1, maxLevel:99, hp:330, atk:76, rcv:0,
      passiveSkill:{ name:'Regrow', text:'Heal +1% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.01 } },
      activeSkill:{ name:'Vine Whip', cd:8, text:'Deal Wood damage (placeholder).', params:{ dmg:94 } },
      img:'images/Monsters/M027-Vine_Lurker/M027-Vine_Lurker.png', mini:'images/Monsters/M027-Vine_Lurker/M027-Vine_Lurker-mini.png' },
    { id:'028', name:'Moss Brute', element:'wood', rarity:2, level:1, maxLevel:99, hp:380, atk:68, rcv:0,
      passiveSkill:{ name:'Mossy Hide', text:'Take -7% damage (placeholder).', params:{ damageReduction:0.07 } },
      activeSkill:{ name:'Root Bash', cd:8, text:'Convert 1 tile to Wood (placeholder).', params:{ convert:{ count:1, to:'wood' } } },
      img:'images/Monsters/M028-Moss_Brute/M028-Moss_Brute.png', mini:'images/Monsters/M028-Moss_Brute/M028-Moss_Brute-mini.png' },
    { id:'029', name:'Lumen Idol', element:'light', rarity:2, level:1, maxLevel:99, hp:300, atk:82, rcv:0,
      passiveSkill:{ name:'Radiance', text:'Light damage +5% (placeholder).', params:{ lightDmgBonus:0.05 } },
      activeSkill:{ name:'Light Pulse', cd:8, text:'Convert 2 tiles to Light (placeholder).', params:{ convert:{ count:2, to:'light' } } },
      img:'images/Monsters/M029-Lumen_Idol/M029-Lumen_Idol.png', mini:'images/Monsters/M029-Lumen_Idol/M029-Lumen_Idol-mini.png' },
    { id:'030', name:'Dusk Hound', element:'dark', rarity:2, level:1, maxLevel:99, hp:290, atk:88, rcv:0,
      passiveSkill:{ name:'Shadow Pounce', text:'ATK +6% (placeholder).', params:{ atkBonus:0.06 } },
      activeSkill:{ name:'Dark Fang', cd:7, text:'Deal Dark damage (placeholder).', params:{ dmg:98 } },
      img:'images/Monsters/M030-Dusk_Hound/M030-Dusk_Hound.png', mini:'images/Monsters/M030-Dusk_Hound/M030-Dusk_Hound-mini.png' },

    // 3★ (031-040)
    { id:'031', name:'Inferno Raptor', element:'fire', rarity:3, level:1, maxLevel:99, hp:480, atk:110, rcv:0,
      passiveSkill:{ name:'Burning Hunt', text:'ATK +8% (placeholder).', params:{ atkBonus:0.08 } },
      activeSkill:{ name:'Raptor Rush', cd:8, text:'Deal Fire damage (placeholder).', params:{ dmg:130 } },
      img:'images/Monsters/M031-Inferno_Raptor/M031-Inferno_Raptor.png', mini:'images/Monsters/M031-Inferno_Raptor/M031-Inferno_Raptor-mini.png' },
    { id:'032', name:'Ash Sentinel', element:'fire', rarity:3, level:1, maxLevel:99, hp:520, atk:105, rcv:0,
      passiveSkill:{ name:'Ash Armor', text:'Take -10% damage (placeholder).', params:{ damageReduction:0.10 } },
      activeSkill:{ name:'Ember Quake', cd:9, text:'Convert 2 tiles to Fire (placeholder).', params:{ convert:{ count:2, to:'fire' } } },
      img:'images/Monsters/M032-Ash_Sentinel/M032-Ash_Sentinel.png', mini:'images/Monsters/M032-Ash_Sentinel/M032-Ash_Sentinel-mini.png' },
    { id:'033', name:'Coral Wraith', element:'water', rarity:3, level:1, maxLevel:99, hp:430, atk:112, rcv:0,
      passiveSkill:{ name:'Undercurrent', text:'Chance to slow (placeholder).', params:{ slowChance:0.08 } },
      activeSkill:{ name:'Coral Spike', cd:8, text:'Deal Water damage (placeholder).', params:{ dmg:132 } },
      img:'images/Monsters/M033-Coral_Wraith/M033-Coral_Wraith.png', mini:'images/Monsters/M033-Coral_Wraith/M033-Coral_Wraith-mini.png' },
    { id:'034', name:'Glacier Stag', element:'water', rarity:3, level:1, maxLevel:99, hp:500, atk:102, rcv:0,
      passiveSkill:{ name:'Frost Coat', text:'Take -10% damage (placeholder).', params:{ damageReduction:0.10 } },
      activeSkill:{ name:'Ice Stampede', cd:9, text:'Convert 1 tile to Water and 1 to Heart (placeholder).', params:{ convert:[{count:1,to:'water'},{count:1,to:'heart'}] } },
      img:'images/Monsters/M034-Glacier_Stag/M034-Glacier_Stag.png', mini:'images/Monsters/M034-Glacier_Stag/M034-Glacier_Stag-mini.png' },
    { id:'035', name:'Root Stalker', element:'wood', rarity:3, level:1, maxLevel:99, hp:520, atk:100, rcv:0,
      passiveSkill:{ name:'Verdant Skin', text:'Heal +1% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.01 } },
      activeSkill:{ name:'Root Snare', cd:9, text:'Convert 2 tiles to Wood (placeholder).', params:{ convert:{ count:2, to:'wood' } } },
      img:'images/Monsters/M035-Root_Stalker/M035-Root_Stalker.png', mini:'images/Monsters/M035-Root_Stalker/M035-Root_Stalker-mini.png' },
    { id:'036', name:'Briar Ogre', element:'wood', rarity:3, level:1, maxLevel:99, hp:560, atk:98, rcv:0,
      passiveSkill:{ name:'Thorn Hide', text:'Take -12% damage (placeholder).', params:{ damageReduction:0.12 } },
      activeSkill:{ name:'Briar Slam', cd:8, text:'Deal Wood damage (placeholder).', params:{ dmg:128 } },
      img:'images/Monsters/M036-Briar_Ogre/M036-Briar_Ogre.png', mini:'images/Monsters/M036-Briar_Ogre/M036-Briar_Ogre-mini.png' },
    { id:'037', name:'Halo Revenant', element:'light', rarity:3, level:1, maxLevel:99, hp:450, atk:115, rcv:0,
      passiveSkill:{ name:'Blessed Edge', text:'Light damage +8% (placeholder).', params:{ lightDmgBonus:0.08 } },
      activeSkill:{ name:'Radiant Lance', cd:9, text:'Deal Light damage (placeholder).', params:{ dmg:140 } },
      img:'images/Monsters/M037-Halo_Revenant/M037-Halo_Revenant.png', mini:'images/Monsters/M037-Halo_Revenant/M037-Halo_Revenant-mini.png' },
    { id:'038', name:'Sunsteel Guard', element:'light', rarity:3, level:1, maxLevel:99, hp:520, atk:102, rcv:0,
      passiveSkill:{ name:'Sunsteel', text:'Take -10% damage (placeholder).', params:{ damageReduction:0.10 } },
      activeSkill:{ name:'Solar Flash', cd:9, text:'Convert 2 tiles to Light (placeholder).', params:{ convert:{ count:2, to:'light' } } },
      img:'images/Monsters/M038-Sunsteel_Guard/M038-Sunsteel_Guard.png', mini:'images/Monsters/M038-Sunsteel_Guard/M038-Sunsteel_Guard-mini.png' },
    { id:'039', name:'Void Stinger', element:'dark', rarity:3, level:1, maxLevel:99, hp:420, atk:122, rcv:0,
      passiveSkill:{ name:'Venom Shade', text:'ATK +8% (placeholder).', params:{ atkBonus:0.08 } },
      activeSkill:{ name:'Night Pierce', cd:8, text:'Deal Dark damage (placeholder).', params:{ dmg:145 } },
      img:'images/Monsters/M039-Void_Stinger/M039-Void_Stinger.png', mini:'images/Monsters/M039-Void_Stinger/M039-Void_Stinger-mini.png' },
    { id:'040', name:'Dread Mask', element:'dark', rarity:3, level:1, maxLevel:99, hp:500, atk:108, rcv:0,
      passiveSkill:{ name:'Fear Aura', text:'ATK +5% (placeholder).', params:{ atkBonus:0.05 } },
      activeSkill:{ name:'Shadow Bind', cd:9, text:'Convert 1 tile to Dark and 1 to Heart (placeholder).', params:{ convert:[{count:1,to:'dark'},{count:1,to:'heart'}] } },
      img:'images/Monsters/M040-Dread_Mask/M040-Dread_Mask.png', mini:'images/Monsters/M040-Dread_Mask/M040-Dread_Mask-mini.png' },

    // 4★ (041-050)
    { id:'041', name:'Blaze Minotaur', element:'fire', rarity:4, level:1, maxLevel:99, hp:650, atk:145, rcv:0,
      passiveSkill:{ name:'Rage', text:'ATK +10% (placeholder).', params:{ atkBonus:0.10 } },
      activeSkill:{ name:'Molten Charge', cd:10, text:'Deal Fire damage (placeholder).', params:{ dmg:190 } },
      img:'images/Monsters/M041-Blaze_Minotaur/M041-Blaze_Minotaur.png', mini:'images/Monsters/M041-Blaze_Minotaur/M041-Blaze_Minotaur-mini.png' },
    { id:'042', name:'Lava Basilisk', element:'fire', rarity:4, level:1, maxLevel:99, hp:620, atk:150, rcv:0,
      passiveSkill:{ name:'Molten Scales', text:'Take -12% damage (placeholder).', params:{ damageReduction:0.12 } },
      activeSkill:{ name:'Basilisk Flare', cd:10, text:'Convert 3 tiles to Fire (placeholder).', params:{ convert:{ count:3, to:'fire' } } },
      img:'images/Monsters/M042-Lava_Basilisk/M042-Lava_Basilisk.png', mini:'images/Monsters/M042-Lava_Basilisk/M042-Lava_Basilisk-mini.png' },
    { id:'043', name:'Abyssal Current', element:'water', rarity:4, level:1, maxLevel:99, hp:600, atk:148, rcv:0,
      passiveSkill:{ name:'Deep Chill', text:'Chance to slow (placeholder).', params:{ slowChance:0.12 } },
      activeSkill:{ name:'Crushing Wave', cd:10, text:'Deal Water damage (placeholder).', params:{ dmg:195 } },
      img:'images/Monsters/M043-Abyssal_Current/M043-Abyssal_Current.png', mini:'images/Monsters/M043-Abyssal_Current/M043-Abyssal_Current-mini.png' },
    { id:'044', name:'Frost Colossus', element:'water', rarity:4, level:1, maxLevel:99, hp:700, atk:135, rcv:0,
      passiveSkill:{ name:'Ice Wall', text:'Take -14% damage (placeholder).', params:{ damageReduction:0.14 } },
      activeSkill:{ name:'Glacier Break', cd:11, text:'Convert 2 tiles to Water and 1 to Heart (placeholder).', params:{ convert:[{count:2,to:'water'},{count:1,to:'heart'}] } },
      img:'images/Monsters/M044-Frost_Colossus/M044-Frost_Colossus.png', mini:'images/Monsters/M044-Frost_Colossus/M044-Frost_Colossus-mini.png' },
    { id:'045', name:'Grove Hydra', element:'wood', rarity:4, level:1, maxLevel:99, hp:680, atk:140, rcv:0,
      passiveSkill:{ name:'Regenerate', text:'Heal +2% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.02 } },
      activeSkill:{ name:'Hydra Vines', cd:11, text:'Convert 3 tiles to Wood (placeholder).', params:{ convert:{ count:3, to:'wood' } } },
      img:'images/Monsters/M045-Grove_Hydra/M045-Grove_Hydra.png', mini:'images/Monsters/M045-Grove_Hydra/M045-Grove_Hydra-mini.png' },
    { id:'046', name:'Thorn Cathedral', element:'wood', rarity:4, level:1, maxLevel:99, hp:720, atk:130, rcv:0,
      passiveSkill:{ name:'Thorn Aura', text:'Take -12% damage (placeholder).', params:{ damageReduction:0.12 } },
      activeSkill:{ name:'Cathedral Bloom', cd:11, text:'Convert 2 tiles to Wood and 2 to Heart (placeholder).', params:{ convert:[{count:2,to:'wood'},{count:2,to:'heart'}] } },
      img:'images/Monsters/M046-Thorn_Cathedral/M046-Thorn_Cathedral.png', mini:'images/Monsters/M046-Thorn_Cathedral/M046-Thorn_Cathedral-mini.png' },
    { id:'047', name:'Solar Guardian', element:'light', rarity:4, level:1, maxLevel:99, hp:620, atk:150, rcv:0,
      passiveSkill:{ name:'Solar Edge', text:'Light damage +10% (placeholder).', params:{ lightDmgBonus:0.10 } },
      activeSkill:{ name:'Radiant Burst', cd:11, text:'Deal Light damage (placeholder).', params:{ dmg:200 } },
      img:'images/Monsters/M047-Solar_Guardian/M047-Solar_Guardian.png', mini:'images/Monsters/M047-Solar_Guardian/M047-Solar_Guardian-mini.png' },
    { id:'048', name:'Prism Knight', element:'light', rarity:4, level:1, maxLevel:99, hp:560, atk:158, rcv:0,
      passiveSkill:{ name:'Prismatic', text:'ATK +8% (placeholder).', params:{ atkBonus:0.08 } },
      activeSkill:{ name:'Prism Strike', cd:10, text:'Convert 3 tiles to Light (placeholder).', params:{ convert:{ count:3, to:'light' } } },
      img:'images/Monsters/M048-Prism_Knight/M048-Prism_Knight.png', mini:'images/Monsters/M048-Prism_Knight/M048-Prism_Knight-mini.png' },
    { id:'049', name:'Void Reaper', element:'dark', rarity:4, level:1, maxLevel:99, hp:580, atk:160, rcv:0,
      passiveSkill:{ name:'Shadow Harvest', text:'Dark damage +10% (placeholder).', params:{ darkDmgBonus:0.10 } },
      activeSkill:{ name:'Reap', cd:11, text:'Deal Dark damage (placeholder).', params:{ dmg:210 } },
      img:'images/Monsters/M049-Void_Reaper/M049-Void_Reaper.png', mini:'images/Monsters/M049-Void_Reaper/M049-Void_Reaper-mini.png' },
    { id:'050', name:'Night Cathedral', element:'dark', rarity:4, level:1, maxLevel:99, hp:700, atk:138, rcv:0,
      passiveSkill:{ name:'Dark Ward', text:'Take -14% damage (placeholder).', params:{ damageReduction:0.14 } },
      activeSkill:{ name:'Shadow Bloom', cd:11, text:'Convert 2 tiles to Dark and 2 to Heart (placeholder).', params:{ convert:[{count:2,to:'dark'},{count:2,to:'heart'}] } },
      img:'images/Monsters/M050-Night_Cathedral/M050-Night_Cathedral.png', mini:'images/Monsters/M050-Night_Cathedral/M050-Night_Cathedral-mini.png' },

    // 5★ extra (051-055) to reach 10 total 5★
    { id:'051', name:'Crimson Brute', element:'fire', rarity:5, level:1, maxLevel:99, hp:820, atk:175, rcv:0,
      passiveSkill:{ name:'War Ember', text:'Fire damage +12% (placeholder).', params:{ fireDmgBonus:0.12 } },
      activeSkill:{ name:'Furnace Slam', cd:11, text:'Convert 3 tiles to Fire (placeholder).', params:{ convert:{ count:3, to:'fire' } } },
      img:'images/Monsters/M051-Crimson_Brute/M051-Crimson_Brute.png', mini:'images/Monsters/M051-Crimson_Brute/M051-Crimson_Brute-mini.png' },
    { id:'052', name:'Tide Prime', element:'water', rarity:5, level:1, maxLevel:99, hp:780, atk:182, rcv:0,
      passiveSkill:{ name:'Deep Mist', text:'Chance to slow (placeholder).', params:{ slowChance:0.15 } },
      activeSkill:{ name:'Prime Undertow', cd:11, text:'Convert 3 tiles to Water (placeholder).', params:{ convert:{ count:3, to:'water' } } },
      img:'images/Monsters/M052-Tide_Prime/M052-Tide_Prime.png', mini:'images/Monsters/M052-Tide_Prime/M052-Tide_Prime-mini.png' },
    { id:'053', name:'Worldroot Guardian', element:'wood', rarity:5, level:1, maxLevel:99, hp:900, atk:165, rcv:0,
      passiveSkill:{ name:'Ancient Growth', text:'Heal +2% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.02 } },
      activeSkill:{ name:'Root Cathedral', cd:12, text:'Convert 2 tiles to Wood and 1 to Heart (placeholder).', params:{ convert:[{count:2,to:'wood'},{count:1,to:'heart'}] } },
      img:'images/Monsters/M053-Worldroot_Guardian/M053-Worldroot_Guardian.png', mini:'images/Monsters/M053-Worldroot_Guardian/M053-Worldroot_Guardian-mini.png' },
    { id:'054', name:'Solar Herald', element:'light', rarity:5, level:1, maxLevel:99, hp:760, atk:190, rcv:0,
      passiveSkill:{ name:'Radiant Duty', text:'Light damage +12% (placeholder).', params:{ lightDmgBonus:0.12 } },
      activeSkill:{ name:'Herald Pulse', cd:11, text:'Convert 3 tiles to Light (placeholder).', params:{ convert:{ count:3, to:'light' } } },
      img:'images/Monsters/M054-Solar_Herald/M054-Solar_Herald.png', mini:'images/Monsters/M054-Solar_Herald/M054-Solar_Herald-mini.png' },
    { id:'055', name:'Abyss Herald', element:'dark', rarity:5, level:1, maxLevel:99, hp:740, atk:195, rcv:0,
      passiveSkill:{ name:'Abyss Duty', text:'Dark damage +12% (placeholder).', params:{ darkDmgBonus:0.12 } },
      activeSkill:{ name:'Herald Rend', cd:11, text:'Convert 3 tiles to Dark (placeholder).', params:{ convert:{ count:3, to:'dark' } } },
      img:'images/Monsters/M055-Abyss_Herald/M055-Abyss_Herald.png', mini:'images/Monsters/M055-Abyss_Herald/M055-Abyss_Herald-mini.png' },

    // 7★ (056-060)
    { id:'056', name:'Volcanic Tyrant', element:'fire', rarity:7, level:1, maxLevel:99, hp:1200, atk:290, rcv:0,
      passiveSkill:{ name:'Magma Crown', text:'Fire damage +18% (placeholder).', params:{ fireDmgBonus:0.18 } },
      activeSkill:{ name:'Magma Beam', cd:13, text:'Deal heavy Fire damage (placeholder).', params:{ dmg:520 } },
      img:'images/Monsters/M056-Volcanic_Tyrant/M056-Volcanic_Tyrant.png', mini:'images/Monsters/M056-Volcanic_Tyrant/M056-Volcanic_Tyrant-mini.png' },
    { id:'057', name:'Sunforge Chimera', element:'fire', rarity:7, level:1, maxLevel:99, hp:1100, atk:305, rcv:0,
      passiveSkill:{ name:'Forge Heat', text:'ATK +12% (placeholder).', params:{ atkBonus:0.12 } },
      activeSkill:{ name:'Forge Burst', cd:13, text:'Convert 5 tiles to Fire (placeholder).', params:{ convert:{ count:5, to:'fire' } } },
      img:'images/Monsters/M057-Sunforge_Chimera/M057-Sunforge_Chimera.png', mini:'images/Monsters/M057-Sunforge_Chimera/M057-Sunforge_Chimera-mini.png' },
    { id:'058', name:'Abyss Leviathan', element:'water', rarity:7, level:1, maxLevel:99, hp:1250, atk:280, rcv:0,
      passiveSkill:{ name:'Deep Dominion', text:'Water damage +18% (placeholder).', params:{ waterDmgBonus:0.18 } },
      activeSkill:{ name:'Abyss Surge', cd:13, text:'Deal heavy Water damage (placeholder).', params:{ dmg:500 } },
      img:'images/Monsters/M058-Abyss_Leviathan/M058-Abyss_Leviathan.png', mini:'images/Monsters/M058-Abyss_Leviathan/M058-Abyss_Leviathan-mini.png' },
    { id:'059', name:'Worldtree Apex', element:'wood', rarity:7, level:1, maxLevel:99, hp:1300, atk:270, rcv:0,
      passiveSkill:{ name:'Apex Growth', text:'Heal +3% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.03 } },
      activeSkill:{ name:'Apex Roots', cd:14, text:'Convert 4 tiles to Wood and 2 to Heart (placeholder).', params:{ convert:[{count:4,to:'wood'},{count:2,to:'heart'}] } },
      img:'images/Monsters/M059-Worldtree_Apex/M059-Worldtree_Apex.png', mini:'images/Monsters/M059-Worldtree_Apex/M059-Worldtree_Apex-mini.png' },
    { id:'060', name:'Prism Archon', element:'light', rarity:7, level:1, maxLevel:99, hp:1150, atk:310, rcv:0,
      passiveSkill:{ name:'Prism Law', text:'Light damage +18% (placeholder).', params:{ lightDmgBonus:0.18 } },
      activeSkill:{ name:'Archon Ray', cd:14, text:'Deal heavy Light damage (placeholder).', params:{ dmg:540 } },
      img:'images/Monsters/M060-Prism_Archon/M060-Prism_Archon.png', mini:'images/Monsters/M060-Prism_Archon/M060-Prism_Archon-mini.png' },

    // 8★ (061-065)
    { id:'061', name:'Infernal Emperor', element:'fire', rarity:8, level:1, maxLevel:99, hp:1500, atk:380, rcv:0,
      passiveSkill:{ name:'Imperial Flame', text:'Fire damage +22% (placeholder).', params:{ fireDmgBonus:0.22 } },
      activeSkill:{ name:'Emperor Nova', cd:15, text:'Deal massive Fire damage (placeholder).', params:{ dmg:720 } },
      img:'images/Monsters/M061-Infernal_Emperor/M061-Infernal_Emperor.png', mini:'images/Monsters/M061-Infernal_Emperor/M061-Infernal_Emperor-mini.png' },
    { id:'062', name:'Tidal Empress', element:'water', rarity:8, level:1, maxLevel:99, hp:1450, atk:390, rcv:0,
      passiveSkill:{ name:'Imperial Tide', text:'Water damage +22% (placeholder).', params:{ waterDmgBonus:0.22 } },
      activeSkill:{ name:'Empress Break', cd:15, text:'Deal massive Water damage (placeholder).', params:{ dmg:730 } },
      img:'images/Monsters/M062-Tidal_Empress/M062-Tidal_Empress.png', mini:'images/Monsters/M062-Tidal_Empress/M062-Tidal_Empress-mini.png' },
    { id:'063', name:'Verdant Emperor', element:'wood', rarity:8, level:1, maxLevel:99, hp:1600, atk:350, rcv:0,
      passiveSkill:{ name:'Imperial Growth', text:'Heal +4% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.04 } },
      activeSkill:{ name:'Emerald Crown', cd:15, text:'Convert 5 tiles to Wood and 3 to Heart (placeholder).', params:{ convert:[{count:5,to:'wood'},{count:3,to:'heart'}] } },
      img:'images/Monsters/M063-Verdant_Emperor/M063-Verdant_Emperor.png', mini:'images/Monsters/M063-Verdant_Emperor/M063-Verdant_Emperor-mini.png' },
    { id:'064', name:'Solar Empress', element:'light', rarity:8, level:1, maxLevel:99, hp:1400, atk:400, rcv:0,
      passiveSkill:{ name:'Imperial Radiance', text:'Light damage +22% (placeholder).', params:{ lightDmgBonus:0.22 } },
      activeSkill:{ name:'Solar Crown', cd:15, text:'Deal massive Light damage (placeholder).', params:{ dmg:760 } },
      img:'images/Monsters/M064-Solar_Empress/M064-Solar_Empress.png', mini:'images/Monsters/M064-Solar_Empress/M064-Solar_Empress-mini.png' },
    { id:'065', name:'Abyss Emperor', element:'dark', rarity:8, level:1, maxLevel:99, hp:1420, atk:398, rcv:0,
      passiveSkill:{ name:'Imperial Void', text:'Dark damage +22% (placeholder).', params:{ darkDmgBonus:0.22 } },
      activeSkill:{ name:'Void Crown', cd:15, text:'Deal massive Dark damage (placeholder).', params:{ dmg:755 } },
      img:'images/Monsters/M065-Abyss_Emperor/M065-Abyss_Emperor.png', mini:'images/Monsters/M065-Abyss_Emperor/M065-Abyss_Emperor-mini.png' },

    // 9★ (066-070)
    { id:'066', name:'Phoenix Dominion', element:'fire', rarity:9, level:1, maxLevel:99, hp:1800, atk:460, rcv:0,
      passiveSkill:{ name:'Dominion Flame', text:'Fire damage +26% (placeholder).', params:{ fireDmgBonus:0.26 } },
      activeSkill:{ name:'Dominion Blaze', cd:16, text:'Deal extreme Fire damage (placeholder).', params:{ dmg:920 } },
      img:'images/Monsters/M066-Phoenix_Dominion/M066-Phoenix_Dominion.png', mini:'images/Monsters/M066-Phoenix_Dominion/M066-Phoenix_Dominion-mini.png' },
    { id:'067', name:'Leviathan Dominion', element:'water', rarity:9, level:1, maxLevel:99, hp:1750, atk:475, rcv:0,
      passiveSkill:{ name:'Dominion Tide', text:'Water damage +26% (placeholder).', params:{ waterDmgBonus:0.26 } },
      activeSkill:{ name:'Dominion Surge', cd:16, text:'Deal extreme Water damage (placeholder).', params:{ dmg:930 } },
      img:'images/Monsters/M067-Leviathan_Dominion/M067-Leviathan_Dominion.png', mini:'images/Monsters/M067-Leviathan_Dominion/M067-Leviathan_Dominion-mini.png' },
    { id:'068', name:'Worldroot Dominion', element:'wood', rarity:9, level:1, maxLevel:99, hp:2000, atk:430, rcv:0,
      passiveSkill:{ name:'Dominion Growth', text:'Heal +5% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.05 } },
      activeSkill:{ name:'Dominion Roots', cd:16, text:'Convert 6 tiles to Wood and 4 to Heart (placeholder).', params:{ convert:[{count:6,to:'wood'},{count:4,to:'heart'}] } },
      img:'images/Monsters/M068-Worldroot_Dominion/M068-Worldroot_Dominion.png', mini:'images/Monsters/M068-Worldroot_Dominion/M068-Worldroot_Dominion-mini.png' },
    { id:'069', name:'Solar Dominion II', element:'light', rarity:9, level:1, maxLevel:99, hp:1720, atk:485, rcv:0,
      passiveSkill:{ name:'Dominion Radiance', text:'Light damage +26% (placeholder).', params:{ lightDmgBonus:0.26 } },
      activeSkill:{ name:'Dominion Ray', cd:16, text:'Deal extreme Light damage (placeholder).', params:{ dmg:940 } },
      img:'images/Monsters/M069-Solar_Dominion_II/M069-Solar_Dominion_II.png', mini:'images/Monsters/M069-Solar_Dominion_II/M069-Solar_Dominion_II-mini.png' },
    { id:'070', name:'Abyss Dominion', element:'dark', rarity:9, level:1, maxLevel:99, hp:1700, atk:490, rcv:0,
      passiveSkill:{ name:'Dominion Void', text:'Dark damage +26% (placeholder).', params:{ darkDmgBonus:0.26 } },
      activeSkill:{ name:'Dominion Eclipse', cd:16, text:'Deal extreme Dark damage (placeholder).', params:{ dmg:945 } },
      img:'images/Monsters/M070-Abyss_Dominion/M070-Abyss_Dominion.png', mini:'images/Monsters/M070-Abyss_Dominion/M070-Abyss_Dominion-mini.png' },

    // 10★ (071-075)
    { id:'071', name:'Dawnfire Avatar', element:'fire', rarity:10, level:1, maxLevel:99, hp:2400, atk:580, rcv:0,
      passiveSkill:{ name:'Avatar Flame', text:'Fire damage +30% (placeholder).', params:{ fireDmgBonus:0.30 } },
      activeSkill:{ name:'Avatar Nova', cd:17, text:'Deal ultimate Fire damage (placeholder).', params:{ dmg:1200 } },
      img:'images/Monsters/M071-Dawnfire_Avatar/M071-Dawnfire_Avatar.png', mini:'images/Monsters/M071-Dawnfire_Avatar/M071-Dawnfire_Avatar-mini.png' },
    { id:'072', name:'Celestial Tide Avatar', element:'water', rarity:10, level:1, maxLevel:99, hp:2350, atk:595, rcv:0,
      passiveSkill:{ name:'Avatar Tide', text:'Water damage +30% (placeholder).', params:{ waterDmgBonus:0.30 } },
      activeSkill:{ name:'Avatar Tsunami', cd:17, text:'Deal ultimate Water damage (placeholder).', params:{ dmg:1220 } },
      img:'images/Monsters/M072-Celestial_Tide_Avatar/M072-Celestial_Tide_Avatar.png', mini:'images/Monsters/M072-Celestial_Tide_Avatar/M072-Celestial_Tide_Avatar-mini.png' },
    { id:'073', name:'Primordial Verdant Avatar', element:'wood', rarity:10, level:1, maxLevel:99, hp:2600, atk:540, rcv:0,
      passiveSkill:{ name:'Avatar Growth', text:'Heal +6% max HP each turn (placeholder).', params:{ healMaxHpPctPerTurn:0.06 } },
      activeSkill:{ name:'Avatar Cathedral', cd:17, text:'Convert 8 tiles to Wood and 6 to Heart (placeholder).', params:{ convert:[{count:8,to:'wood'},{count:6,to:'heart'}] } },
      img:'images/Monsters/M073-Primordial_Verdant_Avatar/M073-Primordial_Verdant_Avatar.png', mini:'images/Monsters/M073-Primordial_Verdant_Avatar/M073-Primordial_Verdant_Avatar-mini.png' },
    { id:'074', name:'Arc Lumen Avatar', element:'light', rarity:10, level:1, maxLevel:99, hp:2300, atk:610, rcv:0,
      passiveSkill:{ name:'Avatar Radiance', text:'Light damage +30% (placeholder).', params:{ lightDmgBonus:0.30 } },
      activeSkill:{ name:'Avatar Judgement', cd:17, text:'Deal ultimate Light damage (placeholder).', params:{ dmg:1240 } },
      img:'images/Monsters/M074-Arc_Lumen_Avatar/M074-Arc_Lumen_Avatar.png', mini:'images/Monsters/M074-Arc_Lumen_Avatar/M074-Arc_Lumen_Avatar-mini.png' },
    { id:'075', name:'Umbral Eclipse Avatar', element:'dark', rarity:10, level:1, maxLevel:99, hp:2320, atk:605, rcv:0,
      passiveSkill:{ name:'Avatar Void', text:'Dark damage +30% (placeholder).', params:{ darkDmgBonus:0.30 } },
      activeSkill:{ name:'Avatar Eclipse', cd:17, text:'Deal ultimate Dark damage (placeholder).', params:{ dmg:1230 } },
      img:'images/Monsters/M075-Umbral_Eclipse_Avatar/M075-Umbral_Eclipse_Avatar.png', mini:'images/Monsters/M075-Umbral_Eclipse_Avatar/M075-Umbral_Eclipse_Avatar-mini.png' }
  ];
})();

